<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "api" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'The subscribers list does not exist.' => 'The subscribers list does not exist.',
  'The subscribers list does not have any custom field defined.' => 'The subscribers list does not have any custom field defined.',
  'The campaign does not exist.' => 'The campaign does not exist.',
  'Only POST requests allowed for this endpoint.' => 'Only POST requests allowed for this endpoint.',
  'You have reached the maximum number of allowed campaigns.' => 'You have reached the maximum number of allowed campaigns.',
  'Please provide a list for this campaign.' => 'Please provide a list for this campaign.',
  'Provided list does not exist.' => 'Provided list does not exist.',
  'Provided list segment does not exist.' => 'Provided list segment does not exist.',
  'Provided template does not exist.' => 'Provided template does not exist.',
  'It does not seem that you have selected an archive.' => 'It does not seem that you have selected an archive.',
  'Your archive does not seem to be a valid zip file.' => 'Your archive does not seem to be a valid zip file.',
  'Cannot write archive in the temporary location.' => 'Cannot write archive in the temporary location.',
  'Please provide a template for your campaign.' => 'Please provide a template for your campaign.',
  'Only PUT requests allowed for this endpoint.' => 'Only PUT requests allowed for this endpoint.',
  'Unable to copy the campaign.' => 'Unable to copy the campaign.',
  'The campaign does not allow marking it as sent!' => 'The campaign does not allow marking it as sent!',
  'Only DELETE requests allowed for this endpoint.' => 'Only DELETE requests allowed for this endpoint.',
  'This campaign cannot be removed now.' => 'This campaign cannot be removed now.',
  'Customer creation is disabled.' => 'Customer creation is disabled.',
  'Unable to find the specified country, please double check the spelling!' => 'Unable to find the specified country, please double check the spelling!',
  'Unable to find the specified zone, please double check the spelling!' => 'Unable to find the specified zone, please double check the spelling!',
  'The template does not exist.' => 'The template does not exist.',
  'The list does not exist.' => 'The list does not exist.',
  'You have reached the maximum number of allowed lists.' => 'You have reached the maximum number of allowed lists.',
  'Unable to copy the list.' => 'Unable to copy the list.',
  'The email does not exist.' => 'The email does not exist.',
  'The subscriber does not exist.' => 'The subscriber does not exist.',
  'The url hash does not exist.' => 'The url hash does not exist.',
  'The subscriber does not exist in this list.' => 'The subscriber does not exist in this list.',
  'Please provide the subscriber email address.' => 'Please provide the subscriber email address.',
  'Please provide a valid email address.' => 'Please provide a valid email address.',
  'The subscriber already exists in this list.' => 'The subscriber already exists in this list.',
  'This email address is blacklisted.' => 'This email address is blacklisted.',
  'The field {field} is required by the list but it has not been provided!' => 'The field {field} is required by the list but it has not been provided!',
  'The field {field} contains multiple values, which is not supported right now!' => 'The field {field} contains multiple values, which is not supported right now!',
  'Unable to save the subscriber!' => 'Unable to save the subscriber!',
  'Another subscriber with this email address already exists in this list.' => 'Another subscriber with this email address already exists in this list.',
  'Your IP address is not allowed to access this server.' => 'Your IP address is not allowed to access this server.',
  'Invalid API request params. Please refer to the documentation.' => 'Invalid API request params. Please refer to the documentation.',
  'Service Unavailable.' => 'Service Unavailable.',
);
