<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "api_keys" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Key' => 'Key',
  'Customer' => 'Customer',
  'Public key' => 'Public key',
  'Private key' => 'Private key',
  'Ip whitelist' => 'Ip whitelist',
  'Ip blacklist' => 'Ip blacklist',
  '123.123.123.123, 111.111.111.111' => '123.123.123.123, 111.111.111.111',
  '231.231.231.231, 222.222.222.222' => '231.231.231.231, 222.222.222.222',
  'Generate new key' => 'Generate new key',
  'Your API url is: {url}' => 'Your API url is: {url}',
  'Api keys' => 'Api keys',
  'A new API access has been added:<br />Public key: {public} <br />Private key: {private}' => 'A new API access has been added:<br />Public key: {public} <br />Private key: {private}',
  'Update api keys' => 'Update api keys',
  'Requested API access has been successfully removed!' => 'Requested API access has been successfully removed!',
);
