<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "cronjobs" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Application cron jobs' => 'Application cron jobs',
  'Description' => 'Description',
  'Cronjob' => 'Cronjob',
  'Please note that all the cron jobs below must be added on your server in order for the application to work properly.' => 'Please note that all the cron jobs below must be added on your server in order for the application to work properly.',
  'Please consult your web hosting knowledge base in order to understand how these cron jobs must be added on your server.' => 'Please consult your web hosting knowledge base in order to understand how these cron jobs must be added on your server.',
  'View cron jobs list' => 'View cron jobs list',
  'Cron jobs list' => 'Cron jobs list',
);
