<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "email_blacklist" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Blacklist monitors will monitor the email blacklist and when emails matching the conditions will be added in the blacklist, they will be removed automatically and subscribers matching the emails will be marked back as confirmed.' => 'Blacklist monitors will monitor the email blacklist and when emails matching the conditions will be added in the blacklist, they will be removed automatically and subscribers matching the emails will be marked back as confirmed.',
  'Please note that in order for the monitoring to work, you need to add the following cron job, which runs once per hour:' => 'Please note that in order for the monitoring to work, you need to add the following cron job, which runs once per hour:',
  'Import from CSV file' => 'Import from CSV file',
  'If unsure about how to format your file, do an export first and see how the file looks.' => 'If unsure about how to format your file, do an export first and see how the file looks.',
  'Are you sure you want to run this action?' => 'Are you sure you want to run this action?',
  'Filters' => 'Filters',
  'Submit' => 'Submit',
  'Blacklisted emails' => 'Blacklisted emails',
  'Please note, the csv file must contain a header with at least the email column.' => 'Please note, the csv file must contain a header with at least the email column.',
  'Approve' => 'Approve',
  'When people enter their email addresses as a {suggestion} to be added in the global blacklist so that they will never receive emails from this source again, those will appear here and you can approve or delete them.' => 'When people enter their email addresses as a {suggestion} to be added in the global blacklist so that they will never receive emails from this source again, those will appear here and you can approve or delete them.',
  'Suggestion' => 'Suggestion',
  'Once you approve an email, it will be deleted from this list and added in the global blacklist automatically!' => 'Once you approve an email, it will be deleted from this list and added in the global blacklist automatically!',
  'Action' => 'Action',
  'Email' => 'Email',
  'Reason' => 'Reason',
  'Date start' => 'Date start',
  'Date end' => 'Date end',
  'Blacklist monitors' => 'Blacklist monitors',
  'Create a new blacklist monitor.' => 'Create a new blacklist monitor.',
  'Update blacklist monitor.' => 'Update blacklist monitor.',
  'Cannot open export temporary file!' => 'Cannot open export temporary file!',
  'Your file does not contain the header with the fields title!' => 'Your file does not contain the header with the fields title!',
  'Your file has been successfuly imported, from {count} records, {total} were imported!' => 'Your file has been successfuly imported, from {count} records, {total} were imported!',
  'Action completed successfully, deleted {n} emails!' => 'Action completed successfully, deleted {n} emails!',
  'Add a new email address to blacklist.' => 'Add a new email address to blacklist.',
  'Update blacklisted email address.' => 'Update blacklisted email address.',
  'Date added' => 'Date added',
  'Email blacklist suggestions' => 'Email blacklist suggestions',
  'The item has been successfully approved and moved into the global blacklist!' => 'The item has been successfully approved and moved into the global blacklist!',
  '{attribute} "{value}" has already been blocked.' => '{attribute} "{value}" has already been blocked.',
  'Ip address' => 'Ip address',
  'User agent' => 'User agent',
  'Subscriber' => 'Subscriber',
  'Matched regex: {regex}' => 'Matched regex: {regex}',
  'Invalid email address format!' => 'Invalid email address format!',
  'Blacklisted' => 'Blacklisted',
  'Monitor' => 'Monitor',
  'Name' => 'Name',
  'Email condition' => 'Email condition',
  'Email match' => 'Email match',
  'Reason condition' => 'Reason condition',
  'Reason match' => 'Reason match',
  'Condition operator' => 'Condition operator',
  'Notifications to' => 'Notifications to',
  'Name your monitor for easier identification' => 'Name your monitor for easier identification',
  'How to match against the blacklisted email address' => 'How to match against the blacklisted email address',
  'The text to match against the email address' => 'The text to match against the email address',
  'How to match against the blacklisted reason' => 'How to match against the blacklisted reason',
  'The text to match against the blacklist reason. Use the [EMPTY] tag to match empty content' => 'The text to match against the blacklist reason. Use the [EMPTY] tag to match empty content',
  'What operator to use between the conditions' => 'What operator to use between the conditions',
  'Where to send notifications when the conditions are met. Separate multiple email addresses with a comma' => 'Where to send notifications when the conditions are met. Separate multiple email addresses with a comma',
  'Greylisted' => 'Greylisted',
  'The email address {email} is already in your blacklist!' => 'The email address {email} is already in your blacklist!',
  'Blacklist' => 'Blacklist',
  '{app} is an email-marketing service that serves companies of all shapes and sizes.' => '{app} is an email-marketing service that serves companies of all shapes and sizes.',
  'With several users/companies sending campaigns to hundreds of millions of recipients, we\'re bound to get abuse reports. ' => 'With several users/companies sending campaigns to hundreds of millions of recipients, we\'re bound to get abuse reports. ',
  'We take abuse reports seriously, if you believe a customer is sending unsolicited and or spam email, please report abuse immediately.' => 'We take abuse reports seriously, if you believe a customer is sending unsolicited and or spam email, please report abuse immediately.',
  'By completing the form above you will permanently block your email address from receiving any email from {app} customers for the foreseeable future. This could also block genuine emails that you do want to receive from companies or websites that use our service.' => 'By completing the form above you will permanently block your email address from receiving any email from {app} customers for the foreseeable future. This could also block genuine emails that you do want to receive from companies or websites that use our service.',
  'Block my address' => 'Block my address',
  'Block email address' => 'Block email address',
);
