<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "email_templates" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Preview' => 'Preview',
  'Upload template' => 'Upload template',
  'Upload template archive' => 'Upload template archive',
  'Upload archive' => 'Upload archive',
  'Email templates gallery' => 'Email templates gallery',
  'Unable to copy the template!' => 'Unable to copy the template!',
  'The template has been successfully copied!' => 'The template has been successfully copied!',
  'You successfully created a new email template!' => 'You successfully created a new email template!',
  'Create a new email template' => 'Create a new email template',
  'You successfully updated your email template!' => 'You successfully updated your email template!',
  'Update email template' => 'Update email template',
  'Please wait while saving your template screenshot...' => 'Please wait while saving your template screenshot...',
  'Your template was successfully deleted!' => 'Your template was successfully deleted!',
  'Template' => 'Template',
  'Template uid' => 'Template uid',
  'Customer' => 'Customer',
  'Name' => 'Name',
  'Content' => 'Content',
  'Content hash' => 'Content hash',
  'Create screenshot' => 'Create screenshot',
  'Screenshot' => 'Screenshot',
  'Archive file' => 'Archive file',
  'The name of the template, used for you to make the difference if having to many templates.' => 'The name of the template, used for you to make the difference if having to many templates.',
  'Send a test email using this template' => 'Send a test email using this template',
  'Send a test email' => 'Send a test email',
  'Send test' => 'Send test',
  'Import html from url' => 'Import html from url',
  'Import html template from url' => 'Import html template from url',
  'Please note that your url must contain a valid html email template with absolute paths to resources!' => 'Please note that your url must contain a valid html email template with absolute paths to resources!',
  'Import' => 'Import',
  'The email address {email} does not seem to be valid!' => 'The email address {email} does not seem to be valid!',
  'My email templates' => 'My email templates',
  'Email templates' => 'Email templates',
  'Unable to import the template!' => 'Unable to import the template!',
  'Unable to save the imported template!' => 'Unable to save the imported template!',
  'The template has been successfully imported!' => 'The template has been successfully imported!',
  'Please specify the email address to where we should send the test email.' => 'Please specify the email address to where we should send the test email.',
  'Email delivery is temporary disabled.' => 'Email delivery is temporary disabled.',
  'Cannot send using provided email address(es)!' => 'Cannot send using provided email address(es)!',
  '[TEST TEMPLATE]' => '[TEST TEMPLATE]',
  'Unable to send the test email to {email}!' => 'Unable to send the test email to {email}!',
  'Test email successfully sent to {email}!' => 'Test email successfully sent to {email}!',
);
