<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "emails_blacklist" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Please specify at least the email and/or the reason!' => 'Please specify at least the email and/or the reason!',
  'Please specify the condition!' => 'Please specify the condition!',
);
