<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_payment_gateway_offline" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Offline payment gateway' => 'Offline payment gateway',
  'Offline payments' => 'Offline payments',
  'Offline' => 'Offline',
  'Retrieve payments offline' => 'Retrieve payments offline',
  'Offline payment' => 'Offline payment',
  'Description' => 'Description',
  'The needed details for customers to see and to use in order to make the offline payment' => 'The needed details for customers to see and to use in order to make the offline payment',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
);
