<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_campaign_activity_map" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Campaign activity map' => 'Campaign activity map',
  'Decide whether to show various maps in the campaign overview area.' => 'Decide whether to show various maps in the campaign overview area.',
  'Show opens map' => 'Show opens map',
  'Show clicks map' => 'Show clicks map',
  'Opens at once' => 'Opens at once',
  'Clicks at once' => 'Clicks at once',
  'Show unsubscribes map' => 'Show unsubscribes map',
  'Unsubscribes at once' => 'Unsubscribes at once',
  'Google maps API key' => 'Google maps API key',
  'Whether to show a map with location opens in campaign overview' => 'Whether to show a map with location opens in campaign overview',
  'Whether to show a map with location clicks in campaign overview' => 'Whether to show a map with location clicks in campaign overview',
  'How many open records to load at once per ajax call? More records means more memory usage' => 'How many open records to load at once per ajax call? More records means more memory usage',
  'How many click records to load at once per ajax call? More records means more memory usage' => 'How many click records to load at once per ajax call? More records means more memory usage',
  'Whether to show a map with location from where subscribers unsubscribed in campaign overview' => 'Whether to show a map with location from where subscribers unsubscribed in campaign overview',
  'How many unsubscribe records to load at once per ajax call? More records means more memory usage' => 'How many unsubscribe records to load at once per ajax call? More records means more memory usage',
  'Your google maps API key. It is optional but needed if you go over the free quota assigned by Google' => 'Your google maps API key. It is optional but needed if you go over the free quota assigned by Google',
);
