<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_ckeditor" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'CKeditor options' => 'CKeditor options',
  'Enable filemanager for users' => 'Enable filemanager for users',
  'Enable filemanager for customers' => 'Enable filemanager for customers',
  'Default toolbar' => 'Default toolbar',
  'Filemanager theme' => 'Filemanager theme',
  'Whether to enable the filemanager for users' => 'Whether to enable the filemanager for users',
  'Whether to enable the filemanager for customers' => 'Whether to enable the filemanager for customers',
  'Default toolbar for all editor instances' => 'Default toolbar for all editor instances',
  'The file manager theme' => 'The file manager theme',
  'Filemanager' => 'Filemanager',
);
