<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_recaptcha" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Common' => 'Common',
  'Recaptcha' => 'Recaptcha',
  'Enabled for list forms' => 'Enabled for list forms',
  'Enable for registration' => 'Enable for registration',
  'Enable for login' => 'Enable for login',
  'Enable for forgot password' => 'Enable for forgot password',
  'Site key' => 'Site key',
  'Secret key' => 'Secret key',
  'Whether the feature is enabled for list forms' => 'Whether the feature is enabled for list forms',
  'Whether the feature is enabled for registration' => 'Whether the feature is enabled for registration',
  'Whether the feature is enabled for login' => 'Whether the feature is enabled for login',
  'Whether the feature is enabled for forgot password' => 'Whether the feature is enabled for forgot password',
  'The site key for recaptcha service' => 'The site key for recaptcha service',
  'The secret key for recaptcha service' => 'The secret key for recaptcha service',
);
