<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "extensions" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Uploaded extensions' => 'Uploaded extensions',
  'Upload extension' => 'Upload extension',
  'Name' => 'Name',
  'Description' => 'Description',
  'Version' => 'Version',
  'Author' => 'Author',
  'Website' => 'Website',
  'Extension detail page' => 'Extension detail page',
  'Core extensions' => 'Core extensions',
  'Upload extension archive.' => 'Upload extension archive.',
  'Please note that only zip files are allowed for upload.' => 'Please note that only zip files are allowed for upload.',
  'View extensions' => 'View extensions',
  'Extensions' => 'Extensions',
  'Your extension has been successfully uploaded!' => 'Your extension has been successfully uploaded!',
  'Please select an extension archive for upload!' => 'Please select an extension archive for upload!',
  'The extension "{name}" has been successfully enabled!' => 'The extension "{name}" has been successfully enabled!',
  'The extension "{name}" has been successfully disabled!' => 'The extension "{name}" has been successfully disabled!',
  'The extension "{name}" has been successfully updated!' => 'The extension "{name}" has been successfully updated!',
  'The extension "{name}" has been successfully deleted!' => 'The extension "{name}" has been successfully deleted!',
  'Conducting extensions checks for the fresh install...' => 'Conducting extensions checks for the fresh install...',
  'The extension "{name}" has failed to update!' => 'The extension "{name}" has failed to update!',
  'All extension checks were conducted successfully.' => 'All extension checks were conducted successfully.',
  'Visit website' => 'Visit website',
  'The extension "{name}" needs updating from version {v1} to version {v2}! Please click {here} to run the update!' => 'The extension "{name}" needs updating from version {v1} to version {v2}! Please click {here} to run the update!',
  'The extension does not exists.' => 'The extension does not exists.',
  'The extension is already enabled.' => 'The extension is already enabled.',
  'The extension {ext} require your application to be at least version {version} but you are currently using version {appVersion}.' => 'The extension {ext} require your application to be at least version {version} but you are currently using version {appVersion}.',
  'Enabling the extension {ext} has failed.' => 'Enabling the extension {ext} has failed.',
  'The extension cannot be disabled by configuration.' => 'The extension cannot be disabled by configuration.',
  'The extension could not be disabled.' => 'The extension could not be disabled.',
  'The extension has to be enabled in order to update it.' => 'The extension has to be enabled in order to update it.',
  'The extension is already at the latest version.' => 'The extension is already at the latest version.',
  'The extension could not be updated.' => 'The extension could not be updated.',
  'The extension cannot be deleted by configuration.' => 'The extension cannot be deleted by configuration.',
  'The extension cannot be deleted.' => 'The extension cannot be deleted.',
);
