<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "languages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Available languages' => 'Доступные языки',
  'Upload language pack' => 'Загрузить языковой пакет',
  'Please note that only zip files are allowed for upload.' => 'Пожалуйста, обратите внимание, загружать можно только zip архивы.',
  'Language packs contain executable PHP files, please check the packs before upload.' => 'Language packs contain executable PHP files, please check the packs before upload.',
  'View available languages' => 'View available languages',
  'Languages' => 'Языки',
  'Create new language' => 'Создать новый язык',
  'Update language' => 'Редактировать язык',
  'Your language pack has been successfully uploaded!' => 'Your language pack has been successfully uploaded!',
  'Please select a language pack archive for upload!' => 'Please select a language pack archive for upload!',
  'The archive upload is only allowed for php message source.' => 'The archive upload is only allowed for php message source.',
  'The language directory {dirName} is not valid and was deleted!' => 'The language directory {dirName} is not valid and was deleted!',
  'The language "{languageName}" cannot be saved, failure reason: ' => 'The language "{languageName}" cannot be saved, failure reason: ',
  'Language' => 'Язык',
  'Name' => 'Название',
  'Language code' => 'Код языка',
  'Region code' => 'Код региона',
  'Is default language?' => 'Is default language?',
  'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)' => 'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)',
  '2 letter language code, i.e: en' => '2 letter language code, i.e: en',
  '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough' => '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough',
  'Whether this language is the default language for users/customers that have not set a language' => 'Whether this language is the default language for users/customers that have not set a language',
  'i.e: English - United States' => 'напр.: English - United States',
  'i.e: en' => 'напр.: en',
  'i.e: us' => 'напр.: us',
);
