<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_export" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'CSV export progress' => 'CSV export progress',
  'Back to export options' => 'Back to export options',
  'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.',
  'The export process is starting, please wait...' => 'The export process is starting, please wait...',
  'CSV' => 'CSV',
  'Export segment' => 'Export segment',
  'Export' => 'Export',
  'Click to export' => 'Click to export',
  'Export subscribers from your list segment' => 'Export subscribers from your list segment',
  'Export subscribers' => 'Export subscribers',
  'CSV Export' => 'CSV Export',
  'Your list has no subscribers to export!' => 'Your list has no subscribers to export!',
  'Cannot create the storage directory for your export!' => 'Cannot create the storage directory for your export!',
  'Cannot create the storage file for your export!' => 'Cannot create the storage file for your export!',
  'Cannot open the storage file for your export!' => 'Cannot open the storage file for your export!',
  'The email "{email}" is blacklisted and was not added to the export list.' => 'The email "{email}" is blacklisted and was not added to the export list.',
  'Successfully added the email "{email}" to the export list.' => 'Successfully added the email "{email}" to the export list.',
  'Exported {count} subscribers, from {start} to {end}.' => 'Exported {count} subscribers, from {start} to {end}.',
  'The export is now complete, starting the packing process...' => 'The export is now complete, starting the packing process...',
  'Cannot create the zip archive of your export!' => 'Cannot create the zip archive of your export!',
  'Packing done, your file will be downloaded now, please wait...' => 'Packing done, your file will be downloaded now, please wait...',
  'Please wait, starting another batch...' => 'Please wait, starting another batch...',
  'The export file has been deleted.' => 'The export file has been deleted.',
  'Export subscribers from your list' => 'Export subscribers from your list',
);
