<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_page_types" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Available tags:' => 'Available tags:',
  'List page types' => 'List page types',
  'Update page type' => 'Update page type',
  'Type' => 'Type',
  'Name' => 'Name',
  'Description' => 'Description',
  'Default content' => 'Default content',
  'Full html' => 'Full html',
);
