<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_segments" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Segment' => 'Segment',
  'List' => 'List',
  'Name' => 'Name',
  'Operator match' => 'Operator match',
  'Subscribers count' => 'Subscribers count',
  'Condition' => 'Condition',
  'Operator' => 'Operator',
  'Field' => 'Field',
  'Value' => 'Value',
  'It will be transformed into an empty value' => 'It will be transformed into an empty value',
  'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})' => 'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})',
  'It will be transformed into the current date in the format of Y-m-d (i.e: {date})' => 'It will be transformed into the current date in the format of Y-m-d (i.e: {date})',
  'It requires the birthday custom field value to be in the format of Y-m-d (i.e: {date}) in order to work properly' => 'It requires the birthday custom field value to be in the format of Y-m-d (i.e: {date}) in order to work properly',
  'This segment contains {count} subscribers' => 'This segment contains {count} subscribers',
  'Sorry, but there are no subscribers matching your segment.' => 'Sorry, but there are no subscribers matching your segment.',
  'Defined conditions:' => 'Defined conditions:',
  'Subscribers matching your segment:' => 'Subscribers matching your segment:',
  'Available value tags' => 'Available value tags',
  'Following tags can be used as dynamic values. They will be replaced as shown below.' => 'Following tags can be used as dynamic values. They will be replaced as shown below.',
  'Tag' => 'Tag',
  'Description' => 'Description',
  'Segments' => 'Segments',
  'Your mail list segments' => 'Your mail list segments',
  'List segments' => 'List segments',
  ' List segments' => ' List segments',
  'You are only allowed to add {num} segment conditions.' => 'You are only allowed to add {num} segment conditions.',
  'Current segmentation is too deep and loads too slow, please revise your segment conditions!' => 'Current segmentation is too deep and loads too slow, please revise your segment conditions!',
  'Create a new list segment' => 'Create a new list segment',
  'Update list segment' => 'Update list segment',
  'Your list segment was successfully copied!' => 'Your list segment was successfully copied!',
  'Your list segment was successfully deleted!' => 'Your list segment was successfully deleted!',
);
