<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "transactional_emails" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View transactional emails' => 'View transactional emails',
  'Transactional emails' => 'Transactional emails',
  'Log' => 'Log',
  'Email' => 'Email',
  'Message' => 'Message',
  'Customer' => 'Customer',
  'To email' => 'To email',
  'To name' => 'To name',
  'From email' => 'From email',
  'From name' => 'From name',
  'Reply to email' => 'Reply to email',
  'Reply to name' => 'Reply to name',
  'Subject' => 'Subject',
  'Body' => 'Body',
  'Plain text' => 'Plain text',
  'Priority' => 'Priority',
  'Retries' => 'Retries',
  'Max retries' => 'Max retries',
  'Send at' => 'Send at',
  'This email address is blacklisted!' => 'This email address is blacklisted!',
);
