<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "api" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Service Unavailable.' => 'Service Unavailable.',
  'The subscriber already exists in this list.' => 'The subscriber already exists in this list.',
  'The list does not exist.' => 'The list does not exist.',
  'The subscriber does not exist in this list.' => 'The subscriber does not exist in this list.',
  'Please provide a valid email address.' => 'Please provide a valid email address.',
  'Invalid API request params. Please refer to the documentation.' => 'Invalid API request params. Please refer to the documentation.',
  'The subscribers list does not exist.' => 'The subscribers list does not exist.',
);
