<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "api_keys" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Api keys' => 'Api ключи',
  'Generate new key' => 'Создать новый ключ',
  'Key' => 'Ключ',
  'Customer' => 'Пользователь',
  'Public key' => 'Public ключ',
  'Private key' => 'Private ключ',
  'A new API access has been added:<br />Public key: {public} <br />Private key: {private}' => 'Новый API доступ был добавлен:<br />Public ключ: {public} <br />Private ключ: {private}',
  'Your API url is: {url}' => 'Your API url is: {url}',
);
