<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "articles" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View countries' => 'Просмотреть стран',
  'View zones' => 'Просмотр зон',
  'View articles' => 'Просмотр статей',
  'Articles' => 'Статьи',
  'Published' => 'Опубликована',
  'Unpublished' => 'Unpublished',
  'Article' => 'Article',
  'Title' => 'Заголовок',
  'Slug' => 'Slug',
  'Content' => 'Текст',
  'Categories' => 'Категории',
  'Related articles' => 'Related articles',
  'View article categories' => 'Просмотр категорий статей',
  'Article categories' => 'Категории статей',
  'Category' => 'Категория',
  'Parent' => 'Parent',
  'Name' => 'Название',
  'Description' => 'Описание',
  'Update article' => 'Update article',
  'My article title' => 'Заголовок статьи',
  'my-article-title' => 'my-article-title',
  'Create new article' => 'Создание новой статьи',
  'All articles filled in under this category' => 'All articles filled in under this category',
  'We\'re sorry, but this category doesn\'t have any published article yet!' => 'We\'re sorry, but this category doesn\'t have any published article yet!',
);
