<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "countries" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View countries' => 'Просмотреть странsы',
  'Countries' => 'Страны',
  'Country' => 'Страна',
  'Name' => 'Название',
  'Code' => 'Код',
);
