<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "cron_jobs" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Campaigns sender, runs each minute.' => 'Отправка сообщений каждую минуту.',
  'Transactional email sender, runs once at 2 minutes.' => 'Транзакционные сообщения каждые 2 минуты.',
  'Bounce handler, runs once at 10 minutes.' => 'Баунсы - каждые 10 минут.',
  'Feedback loop handler, runs once at 20 minutes.' => 'FBL - каждые 20 минут.',
  'Delivery/Bounce processor, runs once at 3 minutes.' => 'Delivery/Bounce процессор, каждые 3 минуты.',
  'Daily cleaner, runs once a day.' => 'Ежедневная очистка, каждый день.',
);
