<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "cronjobs" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View cron jobs list' => 'Просмотр команд планировщика',
  'Cron jobs list' => 'Команды планировщика',
  'Application cron jobs' => 'Планировщик системы',
  'Please note that all the cron jobs below must be added on your server in order for the application to work properly.' => 'Please note that all the cron jobs below must be added on your server in order for the application to work properly.',
  'Please consult your web hosting knowledge base in order to understand how these cron jobs must be added on your server.' => 'Please consult your web hosting knowledge base in order to understand how these cron jobs must be added on your server.',
  'Description' => 'Описание',
  'Cronjob' => 'Команда',
);
