<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "currencies" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View currencies' => 'View currencies',
  'Currencies' => 'Currencies',
  'Currency' => 'Currency',
  'Name' => 'Name',
  'Code' => 'Code',
  'Value' => 'Value',
  'Is default' => 'Is default',
  'Update currency' => 'Update currency',
  'Create new currency' => 'Create new currency',
);
