<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "dashboard" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Dashboard' => 'Панель',
  'At a glance' => 'Общий обзор',
  'Customers' => 'Пользователи',
  'More info' => 'Подробнее',
  'Campaigns' => 'Сообщения',
  'No detailed info' => 'Нет подробной инфо',
  'Lists' => 'Рассылки',
  'Segments' => 'Сегменты',
  'Subscribers' => 'Подписчики',
  'Delivery servers' => 'Сервера доставки',
  'Recent customer activity' => 'Недавняя активность пользователей',
  'Are you sure you want to remove all activity messages?' => 'Вы уверены, что хотите удалить все сообщения?',
  'Subscribers growth' => 'Подписчики',
  'Lists growth' => 'Рассылки',
  'Campaigns growth' => 'Сообщения',
  'Delivery vs Bounces' => 'Bounces',
  'Unsubscribe growth' => 'Отписки',
  'Are you sure you want to remove all blacklisted emails?' => 'Вы уверены, что хотите удалить все в черном списке email?',
  'Templates' => 'Шаблоны',
  'API keys' => 'API ключ',
  'Recent activity' => 'Недавняя активность',
  'Delivery, {n} months growth' => 'Доставлено, за {n} последних месяца',
  'Bounce, {n} months growth' => 'Bounce, за {n} 3 последних месяца',
  '{n} months growth' => '{n} months growth',
);
