<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "email_templates" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Your email templates' => 'Your email templates',
  'Email templates' => 'Шаблоны сообщений',
  'Upload template' => 'Загрузить шаблон',
  'Upload template archive' => 'Загрузить архив с шаблоном',
  'Please see <a href="{templateArchiveHref}">this example archive</a> in order to understand how you should format your uploaded archive! Also, please note we only accept zip files.' => 'Пожалуйста посмотрите <a href="{templateArchiveHref}">на пример готового архива</a> для понимания, в каком формате можно импортировать шаблон.',
  'Template' => 'Template',
  'Template uid' => 'Template uid',
  'Customer' => 'Пользователь',
  'Name' => 'Название',
  'Content' => 'Текст шаблона',
  'Content hash' => 'Content hash',
  'Create screenshot' => 'Создать скриншот',
  'Screenshot' => 'Скриншот',
  'Inline css' => 'Встроенный css',
  'Minify' => 'Сжимать',
  'Archive file' => 'Файл архива',
  'The name of the template, used for you to make the difference if having to many templates.' => 'Используйте уникальное название шаблона',
  'Whether the parser should extract the css from the head of the document and inline it for each matching attribute found in the document body.' => 'Нужно ли извлекать стили CSS.',
  'Whether the parser should minify the template to reduce size.' => 'Сжимать или нет архив с шаблоном для уменьшения его размера.',
  'Upload archive' => 'Загрузить архив',
  'Create a new email template' => 'Создание нового шаблона',
  'Import html from url' => 'Import html from url',
  'Import html template from url' => 'Import html template from url',
  'Please note that your url must contain a valid html email template with absolute paths to resources!' => 'Please note that your url must contain a valid html email template with absolute paths to resources!',
  'Import' => 'Import',
  'Email templates gallery' => 'Галерея E-Mail шаблонов',
  'My email templates' => 'Мои шаблоны сообщений',
  'You successfully created a new email template!' => 'You successfully created a new email template!',
  'Update email template' => 'Изменить шаблон',
  'Preview' => 'Предпросмотр',
  'Send a test email using this template' => 'Отправить тестовое сообщение',
  'Send a test email' => 'Отправка тестового сообщения',
  '* if multiple recipients, separate the email addresses by a comma.<br /> * the email tags will not be parsed while sending test emails.<br /> * make sure you save the template changes before you send the test.' => '* если получателей несколько - отделите их запятыми.<br /> * теги не обрабатываются при отправке тестового сообщения.<br /> * убедитесь, что Вы сохранили изменения перед отправкой тестового сообщения.',
  'Send test' => 'Отправить',
  'Please wait while saving your template screenshot...' => 'Please wait while saving your template screenshot...',
  'You successfully updated your email template!' => 'You successfully updated your email template!',
  'Test email successfully sent to {email}!' => 'Test email successfully sent to {email}!',
  'The template has been successfully imported!' => 'The template has been successfully imported!',
  'The template has been successfully copied!' => 'The template has been successfully copied!',
  'Unable to send the test email to {email}!' => 'Unable to send the test email to {email}!',
  'Sort order' => 'Sort order',
  'Email delivery is temporary disabled.' => 'Email delivery is temporary disabled.',
  'Please specify the email address to where we should send the test email.' => 'Please specify the email address to where we should send the test email.',
);
