<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "email_blacklist" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Blacklisted emails' => 'Черный список E-Mail',
  'Email' => 'Email',
  'Subscriber' => 'Подписчик',
  'Reason' => 'Причина',
  'Import from CSV file' => 'Импорт из CSV',
  'Please note, the csv file must contain a header with at least the email column.' => 'Please note, the csv file must contain a header with at least the email column.',
  'If unsure about how to format your file, do an export first and see how the file looks.' => 'If unsure about how to format your file, do an export first and see how the file looks.',
  'Add a new email address to blacklist.' => 'Добавление нового адреса в черный список.',
  'Date added' => 'Дата добавления',
  'Update blacklisted email address.' => 'Update blacklisted email address.',
  'Your file has been successfuly imported, from {count} records, {total} were imported!' => 'Your file has been successfuly imported, from {count} records, {total} were imported!',
);
