<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_ip_location_freegeoip" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Freegeoip.net' => 'Freegeoip.net',
  'Offers IP location data based on the Freegeoip.net web service' => 'Offers IP location data based on the Freegeoip.net web service',
  'Ip location service from Freegeoip.net' => 'Ip location service from Freegeoip.net',
  'Once the the service is enabled, it will start collecting informations each time when a campaign is opened and/or when a link from within a campaign is clicked.' => 'Once the the service is enabled, it will start collecting informations each time when a campaign is opened and/or when a link from within a campaign is clicked.',
  'Status on email open' => 'Status on email open',
  'Status on track url' => 'Status on track url',
  'Status on unsubscribe' => 'Status on unsubscribe',
  'Sort order' => 'Sort order',
  'Whether this service is enabled and can be used' => 'Whether this service is enabled and can be used',
  'Whether to collect ip location information when a campaign email is opened' => 'Whether to collect ip location information when a campaign email is opened',
  'Whether to collect ip location information when a campaign link is clicked and tracked' => 'Whether to collect ip location information when a campaign link is clicked and tracked',
  'Whether to collect ip location information when a subscriber unsubscribes via a campaign' => 'Whether to collect ip location information when a subscriber unsubscribes via a campaign',
  'If multiple location services active, sort order decides which one queries first' => 'If multiple location services active, sort order decides which one queries first',
);
