<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_html_blocks" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Html blocks' => 'Html blocks',
  'Customer area footer' => 'Customer area footer',
  'Html shown in footer area of the customers' => 'Html shown in footer area of the customers',
);
