<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_support_tickets" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Support tickets' => 'Система тикетов',
  'Departments' => 'Отделы',
  'Priorities' => 'Приоритет',
  'Support tickets settings' => 'Настройка системы тикетов',
  'Settings' => 'Настройки',
  'Rating enabled' => 'Рейтинг',
  'Rating timeframe' => 'Время для возможности выставить рейтинг',
  'Inactive tickets close days' => 'Закрывать автоматически тикеты (дней)',
  'Provide support only for these customer groups' => 'Активировать службу поддержки только для данных групп',
  'Whether rating is enabled and customer are able to rate your replies' => 'Whether rating is enabled and customer are able to rate your replies',
  'After how many hours should we deny the customer the ability to rate a staff reply' => 'After how many hours should we deny the customer the ability to rate a staff reply',
  'After how many days inactive tickets should be closed automatically' => 'After how many days inactive tickets should be closed automatically',
  'Open' => 'Open',
  'Waiting staff reply' => 'Ожидает ответа от поддержки',
  'Waiting customer reply' => 'Ожидает ответа от пользователя',
  'Closed' => 'Закрыт',
  'View all' => 'Просмотр всех',
  'Ticket' => 'Тикет',
  'Assigned to' => 'Кому адресовано',
  'Customer' => 'Пользователь',
  'Department' => 'Отдел',
  'Priority' => 'Приоритет',
  'Subject' => 'Тема сообщения',
  'Content' => 'Содержание',
  'Replies' => 'Replies',
  'Rating' => 'Рейтинг',
  'Ip address' => 'IP адрес',
  'Customer (autocomplete enabled)' => 'Customer (autocomplete enabled)',
  'Submit ticket' => 'Отправить запрос',
  'Hello {nameA}, this ticket has been posted by {nameB} and requires your attention. Please read the ticket content below:' => 'Hello {nameA}, this ticket has been posted by {nameB} and requires your attention. Please read the ticket content below:',
  'Posted by {name}' => 'Posted by {name}',
  'At {date}' => 'At {date}',
  'You can follow the url below in order to reply to this ticket:' => 'You can follow the url below in order to reply to this ticket:',
  'Thank you!' => 'Спасибо!',
  '{site} support' => '{site} support',
  '[{site} support] {subject}' => '[{site} support] {subject}',
  'View support ticket' => 'Просмотр тикета',
  'Ticket #{num}' => 'Тикет #{num}',
  'Subject: {subject}' => 'Тема: {subject}',
  'Status' => 'Статус',
  'Date added' => 'Дата создания',
  'Last updated' => 'Обновлено',
  'Reply to this ticket' => 'Ответить на данный тикет',
  'Reply' => 'Reply',
  'User' => 'User',
  'And' => 'Выбрать действие',
  'Close ticket and do not send reply email' => 'Закрыть тикет и не отправлять сообщение на E-Mail',
  'Close ticket and send reply email' => 'Закрыть тикет и отправить сообщение на E-Mail',
  'Send reply' => 'Отправить ответ',
  'Hello {nameA}, this ticket reply has been posted by {nameB} and requires your attention. Please read the ticket reply content below:' => 'Hello {nameA}, this ticket reply has been posted by {nameB} and requires your attention. Please read the ticket reply content below:',
  'Support team' => 'Support team',
  '{site} support team' => '{site} support team',
  'Showing {n} reply:' => 'Showing {n} reply:',
  'Reply #{num}' => 'Reply #{num}',
  'From {ip} at {date}' => 'From {ip} at {date}',
  'Delete this reply' => 'Удалить данный ответ',
  'Rate this reply' => 'Rate this reply',
  'Support tickets priorities' => 'Варианты приоритета тикетов',
  'Name' => 'Название',
  'Support tickets departments' => 'Отделы службы поддержки',
  'Priority: {priority}' => 'Priority: {priority}',
  'This ticket has been assigned to {user} already, replying to it will assign you to the ticket.' => 'This ticket has been assigned to {user} already, replying to it will assign you to the ticket.',
  'Department: {department}' => 'Department: {department}',
  'Showing all {n} replies:' => 'Showing all {n} replies:',
  'Assigned users' => 'Assigned users',
  'Select one or more users assigned to respond to tickets for this department. Selected users will receive emails each time a support ticket is created and this department selected. If no user is selected, then all system users will receive emails.' => 'Select one or more users assigned to respond to tickets for this department. Selected users will receive emails each time a support ticket is created and this department selected. If no user is selected, then all system users will receive emails.',
);
