<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_translate" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Translate extension' => 'Расширение перевода',
  'Translation extension' => 'Перевод расширение',
  'Once enabled, the translate extension will start collecting messages from the application and write them in files if the message is missing from file and the application language is other than english.' => 'После активации, расширение перевода начнем собирать сообщения из приложения и записать их в файлы, если сообщения отсутствуют приложения и файла язык, кроме английского.',
  'Enable automatic translation' => 'Включить автоматический перевод',
  'Enable extensions translation' => 'Включение расширений перевод',
  'Enable writing the missing translations in file.' => 'Разрешить запись отсутствует перевод в файл.',
  'Whether to translate extensions too.' => 'Нужно ли переводить расширений тоже.',
);
