<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_payment_gateway_paypal" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Paypal' => 'Paypal',
  'Retrieve payments using paypal' => 'Retrieve payments using paypal',
  'Paypal payment gateway' => 'Paypal payment gateway',
  'sandbox' => 'sandbox',
  'live' => 'live',
  'Email' => 'Email',
  'Mode' => 'Mode',
  'Your paypal email address where the payments should go' => 'Your paypal email address where the payments should go',
  'Whether the payments are live or run in sanbox' => 'Whether the payments are live or run in sanbox',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
);
