<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_backup_manager" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Backup manager' => 'Резервные копии',
  'Backup snapshots' => 'Доступные резервные копии',
  'Snapshots' => 'Snapshots',
  'Create new backup snapshot' => 'Создать новую резервную копию',
  'Snapshot' => 'Snapshot',
  'Name' => 'Name',
  'Path' => 'Путь',
  'Size' => 'Размер',
  'Meta data' => 'Meta data',
  'Settings' => 'Settings',
  'Storage path' => 'Путь для хранения копий',
  'Auto backup' => 'Автосоздание копий',
  'Auto backup frequency' => 'Расписание (дни)',
  'Keep max backups' => 'Сколько копий хранить',
  'Success notifications' => 'E-Mail для сообщения о успешном создании копии',
  'Error notifications' => 'E-Mail для сообщений про ошибки копирования',
  'The path on this file system where we should store the backups. Please note that your current system user must be able to write there. Also, do not set a path inside your public html folder since doing this will backup the previously made backups!' => 'The path on this file system where we should store the backups. Please note that your current system user must be able to write there. Also, do not set a path inside your public html folder since doing this will backup the previously made backups!',
  'Whether the auto backup is enabled' => 'Whether the auto backup is enabled',
  'Once at how many days the auto backup process should run and create the backup' => 'Once at how many days the auto backup process should run and create the backup',
  'The maximum number of backups the system must keep, older backups are removed to save disk space' => 'The maximum number of backups the system must keep, older backups are removed to save disk space',
  'A single email address, or a list of emails separated by comma, to where the system should send notifications when a backup is completed successfully' => 'A single email address, or a list of emails separated by comma, to where the system should send notifications when a backup is completed successfully',
  'A single email address, or a list of emails separated by comma, to where the system should send notifications when a backup fails' => 'A single email address, or a list of emails separated by comma, to where the system should send notifications when a backup fails',
  'Starting the backup process...' => 'Starting the backup process...',
  'Checking to see if the storage directory exists...' => 'Checking to see if the storage directory exists...',
  'The storage directory does not exist, trying to create it...' => 'The storage directory does not exist, trying to create it...',
  'The storage directory has been created!' => 'The storage directory has been created!',
  'The directory for this backup is: {dir}' => 'The directory for this backup is: {dir}',
  'Checking to see if the directory for this backup exists...' => 'Checking to see if the directory for this backup exists...',
  'The backup directory does not exists, trying to create it...' => 'The backup directory does not exists, trying to create it...',
  'The backup directory has been created.' => 'The backup directory has been created.',
  'Starting the database backup process...' => 'Starting the database backup process...',
  'Database backed up successfully!' => 'Database backed up successfully!',
  'Starting the file system backup process...' => 'Starting the file system backup process...',
  'File system backed up successfully!' => 'File system backed up successfully!',
  'Starting to pack the backup...' => 'Starting to pack the backup...',
  'Done packing the backup!' => 'Done packing the backup!',
  'Backup complete!' => 'Backup complete!',
);
