<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_ckeditor" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'CKeditor options' => 'Варианты CKEditor',
  'Enable filemanager for users' => 'Включить файловый менеджер для администраторов',
  'Enable filemanager for customers' => 'Включить файловый менеджер для пользователей',
  'Default toolbar' => 'Панель инструментов по умолчанию',
  'Whether to enable the filemanager for users' => 'Следует ли включить файловый менеджер для администраторов',
  'Whether to enable the filemanager for customers' => 'Следует ли включить файловый менеджер для пользователей',
  'Default toolbar for all editor instances' => 'По умолчанию панель инструментов для всех экземпляров редактора',
);
