<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "extensions" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View extensions' => 'Вид расширений',
  'Extensions' => 'Расширения',
  'Uploaded extensions' => 'Загруженные расширения',
  'Upload extension' => 'Загрузить расширение',
  'Name' => 'Имя',
  'Description' => 'Описание',
  'Version' => 'Версия',
  'Author' => 'Автор',
  'Website' => 'Сайт',
  'Extension detail page' => 'Расширение странице подробнее',
  'Core extensions' => 'Расширения ядра',
  'Visit website' => 'Посетить сайт',
  'Upload extension archive.' => 'Загрузить расширение архива.',
  'Please note that only zip files are allowed for upload.' => 'Обратите внимание, что только zip-файлы, разрешены для загрузки.',
  'The extension "{name}" has been successfully enabled!' => 'The extension "{name}" has been successfully enabled!',
  'Your extension has been successfully uploaded!' => 'Your extension has been successfully uploaded!',
);
