<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "guest_fail_attempt" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View guest fail attempts' => 'Попытки неудачной авторизации',
  'Guest fail attempts' => 'Неудачная авторизация',
  'Attempt' => 'Attempt',
  'Ip address' => 'Ip адрес',
  'Ip address hash' => 'Хеш Ip адреса',
  'User agent' => 'Браузер пользователя',
  'Place' => 'Место',
  'Customer login' => 'Логин пользователя',
  'Customer register' => 'Customer register',
  'Customer forgot password' => 'Customer forgot password',
);
