<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "languages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View available languages' => 'Просмотр доступных языков',
  'Languages' => 'Языки',
  'Available languages' => 'Доступные языки',
  'Upload language pack' => 'Загрузить языковой пакет',
  'Language' => 'Язык',
  'Name' => 'Имя',
  'Language code' => 'Код языка',
  'Region code' => 'Региональный код',
  'Is default language?' => 'Язык по умолчанию?',
  'Please note that only zip files are allowed for upload.' => 'Обратите внимание, что только zip-файлы разрешены для загрузки.',
  'Language packs contain executable PHP files, please check the packs before upload.' => 'Языковые пакеты содержат исполняемые файлы PHP, проверьте, пожалуйста, пакеты, прежде чем загружать.',
  'Update language' => 'Обновление языка',
  'i.e: English - United States' => 'i.e: English - Соединенные Штаты',
  'i.e: en' => 'i.e: en',
  'i.e: us' => 'i.e: us',
  'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)' => 'Видимый язык имя отличать одном языке, но отдельных регионов (например: между английской (США) и Русский RUS)',
  '2 letter language code, i.e: en' => '2 буквы кода языка, т.е: ru',
  '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough' => '2 буквы, кода региона, т.е. us. Пожалуйста, заполняйте это поле, если это необходимо. В большинстве случаев, кода языка достаточно',
  'Whether this language is the default language for users/customers that have not set a language' => 'Является ли этот язык, языком по умолчанию для администраторов/пользователей, у которых не установлен язык',
  'Create new language' => 'Create new language',
);
