<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_forms" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Forms' => 'Формы',
  'List embed forms' => 'HTML коды форм',
  'Your mail list forms' => 'Your mail list forms',
  'Embed list forms' => 'Формы подписки и отписки на рассылку',
  'Subscribe form' => 'Форма подписки',
  'Unsubscribe form' => 'Форма отписки',
  'Subscribe' => 'Подписаться',
  'Iframe version' => 'Iframe версия',
  'Please type your email address' => 'Пожалуйста, введите Ваш E-Mail адрес',
  'Unsubscribe' => 'Отписаться',
  'Please note, you will have to style the forms below to match the place where you embed them.<br /> You can create better forms by using the <a href="{sdkHref}" target="_blank">PHP-SDK</a> and connect to the provided api.' => 'Используйте различные стили оформления для форм.<br />',
);
