<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_pages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Pages' => 'Страницы',
  'List pages' => 'Список страниц',
  'Select another list page to edit' => 'Выбрать другую страницу для редактирования',
  'Subscribe form' => 'Форма подписки',
  'Pending subscribe' => 'Pending subscribe',
  'Subscription confirmed' => 'Подписка подтверждена',
  'Update Profile' => 'Update Profile',
  'Unsubscribe form' => 'Unsubscribe form',
  'Unsubscribe confirmation' => 'Unsubscribe confirmation',
  'Subscribe confirm email' => 'Subscribe confirm email',
  'Unsubscribe confirm email' => 'Unsubscribe confirm email',
  'Your subscribe form url is:' => 'Адрес URL Вашей формы подписки:',
  'Preview it now!' => 'Предпросмотр',
  'List' => 'List',
  'Type' => 'Type',
  'Content' => 'Текст',
  'The following tag is required but was not found in your content: {tag}' => 'The following tag is required but was not found in your content: {tag}',
  'Подписка' => 'Подписка',
  'Подтверждение подписки' => 'Подтверждение подписки',
  'Подписка подтверждена' => 'Подписка подтверждена',
  'Обновление профиля' => 'Обновление профиля',
  'Отписка' => 'Отписка',
  'Подтверждение отписки' => 'Подтверждение отписки',
  'Письмо с подтверждением подписки' => 'Письмо с подтверждением подписки',
  'Письмо с подтверждением отписки' => 'Письмо с подтверждением отписки',
  'Your unsubscribe form url is:' => 'Your unsubscribe form url is:',
  'Форма подписки' => 'Форма подписки',
  'Подтвердить подписку через E-mail' => 'Подтвердить подписку через E-mail',
  'Форма отписки' => 'Форма отписки',
);
