<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_export" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Export' => 'Экспорт',
  'Export subscribers from your list' => 'Экспорт подписчиков из Вашей рассылки',
  'Export subscribers' => 'Экспорт подписчиков',
  'CSV' => 'CSV',
  'CSV Export' => 'CSV Export',
  'The export process will start shortly. <br /> While the export is running it is recommended you leave this page as it is and wait for the export to finish.<br /> The exporter runs in batches of {subscribersPerBatch} subscribers per file with a pause of {pause} seconds between the batches, therefore the export process might take a while depending on your list size and number of subscribers to export.<br /> This is a tedious process, so sit tight and wait for it to finish.' => 'The export process will start shortly. <br /> While the export is running it is recommended you leave this page as it is and wait for the export to finish.<br /> The exporter runs in batches of {subscribersPerBatch} subscribers per file with a pause of {pause} seconds between the batches, therefore the export process might take a while depending on your list size and number of subscribers to export.<br /> This is a tedious process, so sit tight and wait for it to finish.',
  'CSV export progress' => 'CSV export progress',
  'Back to export options' => 'Back to export options',
  'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.',
  'The export process is starting, please wait...' => 'The export process is starting, please wait...',
  'The export process for list "{listName}" has successfully started, counting {rowsCount} records!' => 'The export process for list "{listName}" has successfully started, counting {rowsCount} records!',
  'Successfully added the email "{email}" to the export list.' => 'Successfully added the email "{email}" to the export list.',
  'Exported {count} subscribers, from {start} to {end}.' => 'Exported {count} subscribers, from {start} to {end}.',
  'The export process for list "{listName}" has successfully ended, processing {rowsCount} records!' => 'The export process for list "{listName}" has successfully ended, processing {rowsCount} records!',
  'The export is now complete, starting the packing process...' => 'The export is now complete, starting the packing process...',
  'Packing done, your file will be downloaded now, please wait...' => 'Packing done, your file will be downloaded now, please wait...',
  'Your list has no subscribers to export!' => 'Your list has no subscribers to export!',
  'Please wait, starting another batch...' => 'Please wait, starting another batch...',
  'The email "{email}" is blacklisted and was not added to the export list.' => 'The email "{email}" is blacklisted and was not added to the export list.',
  'Export segment' => 'Export segment',
);
