<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_segments" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Segments' => 'Сегменты',
  'List segments' => 'Список сегментов',
  'any' => 'любой',
  'all' => 'все',
  'Your mail list segments' => 'Your mail list segments',
  'Segment' => 'Сегмент',
  'List' => 'List',
  'Name' => 'Название',
  'Operator match' => 'Отношение',
  'Subscribers count' => 'Subscribers count',
  'Create a new list segment' => 'Создание нового сегмента',
  'Defined conditions:' => 'Определенные условия:',
  'Add condition' => 'Добавить условие',
  'Subscribers matching your segment:' => 'Subscribers matching your segment:',
  'Condition' => 'Условие',
  'Operator' => 'Оператор',
  'Field' => 'Поле',
  'Value' => 'Значение',
  'is' => 'Равно',
  'is not' => 'Не равно',
  'contains' => 'Содержит',
  'not contains' => 'Не содержит',
  'starts with' => 'Начинается с',
  'ends with' => 'Заканчивается на',
  'is greater than' => 'Больше, чем',
  'is less than' => 'Менее, чем',
  'Remove condition' => 'Удалить условие',
  ' List segments' => 'Список сегментов',
  'Current segmentation is too deep and loads too slow, please revise your segment conditions!' => 'Current segmentation is too deep and loads too slow, please revise your segment conditions!',
  'A new segment called "{segmentName}" has been added to the list "{listName}" successfully!' => 'A new segment called "{segmentName}" has been added to the list "{listName}" successfully!',
  'Update list segment' => 'Update list segment',
  'This segment contains {count} subscribers' => 'This segment contains {count} subscribers',
  'The segment called "{segmentName}" belonging to the list "{listName}" has been successfully updated!' => 'The segment called "{segmentName}" belonging to the list "{listName}" has been successfully updated!',
  'It will be transformed into an empty value' => 'It will be transformed into an empty value',
  'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})' => 'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})',
  'It will be transformed into the current date in the format of Y-m-d (i.e: {date})' => 'It will be transformed into the current date in the format of Y-m-d (i.e: {date})',
  'It requires the birthday custom field value to be in the format of Y-m-d (i.e: {date}) in order to work properly' => 'It requires the birthday custom field value to be in the format of Y-m-d (i.e: {date}) in order to work properly',
  'View available value tags' => 'View available value tags',
  'not starts with' => 'not starts with',
  'not ends with' => 'not ends with',
  'Available value tags' => 'Available value tags',
  'Following tags can be used as dynamic values. They will be replaced as shown below.' => 'Following tags can be used as dynamic values. They will be replaced as shown below.',
  'Tag' => 'Tag',
  'Description' => 'Description',
);
