<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_subscribers" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Subscribers' => 'Подписчики',
  'List subscribers' => 'Список подписчиков',
  'confirmed' => 'Подтвержден',
  'unconfirmed' => 'Не подтвержден',
  'unsubscribed' => 'Отписался',
  'blacklisted' => 'В черном списке',
  'Are you sure you want to unsubscribe this subscriber?' => 'Are you sure you want to unsubscribe this subscriber?',
  'Your mail list subscribers' => 'Your mail list subscribers',
  'Bulk action from source' => 'Массовые операции с абонентами',
  'With selected:' => 'С выбранными:',
  'Subscribe' => 'Подписать',
  'Unsubscribe' => 'Отписать',
  'Delete' => 'Удалить',
  'Found {count} subscribers.' => 'Найдено {count} подписчиков.',
  'Match the subscribers added here against the ones existing in the list and make a bulk action against them!' => 'Массовые операции с подписчиками списка - Вы можете массово подписать или отписать абонентов!',
  'From file' => 'Из файла',
  'From text' => 'Из текста',
  'Action' => 'Действие',
  'Subscriber' => 'Подписчик',
  'List' => 'Список',
  'Unique id' => 'Unique id',
  'Email' => 'Адрес Email',
  'Source' => 'Источник',
  'Ip Address' => 'Ip Адрес',
  'Bulk action from CSV file, one email address per row and/or separated by a comma.' => 'Операции из CSV файла, один e-mail адрес в строку и/или через запятую.',
  'Bulk action from text area, one email address per line and/or separated by a comma.' => 'Операции из текстовой области, один e-mail адрес в строку и/или через запятую.',
  'For all the subscribers found in file/text area take this action!' => 'Над всеми абонентами, выбранных в файле или текстовой области, сделать данное действие!',
  'Sorry, but there are no subscribers to show right now.' => 'Sorry, but there are no subscribers to show right now.',
  'Please note, this is not the list import ability, for list import go to your list overview, followed by Tools box followed by the Import box.' => 'Обратите внимание, что это НЕ ИМПОРТ списка.',
  'Update existing list subscriber.' => 'Update existing list subscriber.',
  'Add a new subscriber to your list.' => 'Добавление нового подписчика в список.',
  'Please confirm your unsubscription' => 'Please confirm your unsubscription',
  'Please check your email and click on the provided unsubscribe link.' => 'Please check your email and click on the provided unsubscribe link.',
  'The subscriber having the email address "{email}" has been successfully unsubscribed from the "{listName}" list!' => 'The subscriber having the email address "{email}" has been successfully unsubscribed from the "{listName}" list!',
  'Confirm subscriber' => 'Confirm subscriber',
  'Are you sure you want to confirm this subscriber?' => 'Are you sure you want to confirm this subscriber?',
  'Subscribe back' => 'Subscribe back',
  'Are you sure you want to subscribe back this unsubscriber?' => 'Are you sure you want to subscribe back this unsubscriber?',
  'Please confirm your subscription' => 'Пожалуйста, подтвердите подписку',
  'A new subscriber having the email address "{email}" has been successfully added to the list "{listName}"!' => 'A new subscriber having the email address "{email}" has been successfully added to the list "{listName}"!',
  'Action completed, {count} subscribers were affected!' => 'Action completed, {count} subscribers were affected!',
  'Подписчик с адресом "{email}" был отписан от рассылки "{listName}" !' => 'Подписчик с адресом "{email}" был отписан от рассылки "{listName}" !',
  'Подписчик с адресом "{email}" был успешно удален из рассылки "{listName}" !' => 'Подписчик с адресом "{email}" был успешно удален из рассылки "{listName}" !',
  'Новый подписчик с e-mail адресом "{email}" был подписан на рассылку "{listName}"!' => 'Новый подписчик с e-mail адресом "{email}" был подписан на рассылку "{listName}"!',
  'Подписчик с адресом "{email}" был успешно обновлен в рассылке "{listName}" !' => 'Подписчик с адресом "{email}" был успешно обновлен в рассылке "{listName}" !',
  'Confirmed' => 'Подтвержден',
  'Unconfirmed' => 'Не подтвержден',
  'Unsubscribed' => 'Отписан',
  'Back to lists' => 'Вернуться в список',
  'Api' => 'Api',
  'Import' => 'Импорт',
  'Web' => 'Web',
  'Blacklisted' => 'Черный список',
  'The subscriber having the email address "{email}" has been successfully removed from the "{listName}" list!' => 'The subscriber having the email address "{email}" has been successfully removed from the "{listName}" list!',
  'The subscriber having the email address "{email}" has been successfully updated in the "{listName}" list!' => 'The subscriber having the email address "{email}" has been successfully updated in the "{listName}" list!',
);
