<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_import" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Import' => 'Импорт',
  'Import subscribers into your list' => 'Import subscribers into your list',
  'Import subscribers' => 'Импорт подписчиков',
  'CSV' => 'CSV',
  'Select file to import' => 'Выберите файл для импорта',
  'Text' => 'Text',
  'Database' => 'Database',
  'Enter details' => 'Введите данные',
  'Import from CSV file' => 'Импорт из CSV файла',
  'Please note, we only accept valid CSV files that contain a header, that is the column names for the data to be imported.<br /> We also have a limit on the file size you are allowed to upload, that is {uploadLimit}.<br /> The import process might fail with some of the files, mainly because these are not correctly formatted or they contain invalid data.<br /> You should first do a test import(in a test list) and see if that goes as planned then do it for your actual list.<br /> <strong>Important</strong>: The CSV file column names will be used to create the list TAGS, if a tag does not exist, it will be created.<br /> You can also click <a href="{exampleArchiveHref}" target="_blank">here</a> to see a csv file example.' => 'Обратите внимание, что файл должен быть правильного формата и содержать нужные столбцы с данными.<br /> Размер импортируемого файла не должен превышать {uploadLimit}.<br /> Ошибка импорта может быть вызвана несовместимостью форматов или не правильными данными.<br /> Рекомендуем сделать пробный импорт в тестовый список чтобы проверить правильность данных.<br /> <strong>Важно</strong>: Названия столбцов файла CSV используются для создания списка ТЕГОВ. Если ТЕГА не существует, то он будет создан.<br /> Вы можете скачать пример готового файла для импорта <a href="{exampleArchiveHref}" target="_blank">ТУТ</a> и вставить свои адреса.',
  'Upload file' => 'Загрузить файл',
  'Import from text file' => 'Импорт из текстового файла',
  'Please note that you should list each email address on a separate line in your text file.<br /> You can also click <a href="{exampleArchiveHref}" target="_blank">here</a> to see a text file example.<br /> We also have a limit on the file size you are allowed to upload, that is {uploadLimit}.' => 'Каждый адрес почты должен быть в новой строке текстового файла.<br /> Скачать пример готового файла для импорта можно по ссылке <a href="{exampleArchiveHref}" target="_blank">ТУТ</a> и использовать просто внеся свои данные.<br /> Размер файла для импорта не должен превышать {uploadLimit}.',
  'Import from external SQL database' => 'Импорт из внешней SQL базы',
  'Please enter your credentials for the external database in order to start the import.' => 'Пожалуйста, внесите данные для доступа к базе MySql для начала импорта.',
  'MySQL' => 'MySQL',
  'Server type' => 'Тип сервера',
  'Hostname' => 'Хост',
  'Port' => 'Порт',
  'Username' => 'Логин',
  'Password' => 'Пароль',
  'Database name' => 'Имя базы данных',
  'Table name' => 'Имя таблицы',
  'Email column' => 'Email колонка',
  'Ignored columns' => 'Игнорировать колонки',
  'i.e: mysql.databaseclusters.com' => 'i.e: mysql.databaseclusters.com',
  'i.e: 3306' => 'i.e: 3306',
  'i.e: mysqlcluser' => 'i.e: mysqlcluser',
  'i.e: superprivatepassword' => 'i.e: superprivatepassword',
  'i.e: my_blog' => 'i.e: my_blog',
  'i.e: tbl_subscribers' => 'i.e: tbl_subscribers',
  'email' => 'email',
  'i.e: id, date_added, status' => 'i.e: id, date_added, status',
  'The server type, if not sure choose mysql' => 'Тип сервера. Если не уверены - выберите MySQL',
  'The hostname of your database server, it can also be the ip address' => 'Адрес сервера базы данных. Это может быть и IP адрес.',
  'The port where your external database server is listening for connections' => 'Укажите порт для подключения к базе данных.',
  'Your username that unique identifies yourself on the database server' => 'Логин для подключения к базе данных.',
  'The password for the username' => 'Укажите пароль для логина.',
  'Your database name as you see it in a tool like PhpMyAdmin' => 'Имя базы данных - как оно отображается в PhpMyAdmin',
  'Your database table name where your emails are stored, as you see it in a tool like PhpMyAdmin' => 'Укажите название таблицы с адресами e-mail, имя, как оно есть в PhpMyAdmin',
  'The column that identified the email address' => 'Колонка с адресами',
  'Which columns should we ignore and not import. Separate multiple columns by a comma' => 'Какие колонки игнорировать. Можно перечислить через запятую',
  'Connect and import' => 'Подключиться и импортировать',
  'CSV Import' => 'CSV Импорт',
  'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your CSV has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.' => 'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your CSV has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.',
  'CSV import progress' => 'CSV import progress',
  'Back to import options' => 'Back to import options',
  'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.',
  'The import process is starting, please wait...' => 'The import process is starting, please wait...',
  'Cannot find the "email" column in your file!' => 'Cannot find the "email" column in your file!',
  'The import process for list "{listName}" has successfully started, counting {rowsCount} records!' => 'The import process for list "{listName}" has successfully started, counting {rowsCount} records!',
  'Found the following column names: {columns}' => 'Found the following column names: {columns}',
  'Checking to see if the tag "{tag}" is defined in your list fields...' => 'Checking to see if the tag "{tag}" is defined in your list fields...',
  'The tag "{tag}" is already defined in your list fields.' => 'The tag "{tag}" is already defined in your list fields.',
  'Checking the list for the email: "{email}"' => 'Checking the list for the email: "{email}"',
  'The email "{email}" was not found, we will try to create it...' => 'The email "{email}" was not found, we will try to create it...',
  'The email "{email}" has been successfully saved.' => 'The email "{email}" has been successfully saved.',
  'The email "{email}" has been found, we will update it.' => 'The email "{email}" has been found, we will update it.',
  'Imported {count} subscribers starting from row {rowStart} and ending with row {rowEnd}! Going further, please wait...' => 'Imported {count} subscribers starting from row {rowStart} and ending with row {rowEnd}! Going further, please wait...',
  'The import process has finished!' => 'Импорт завершен!',
  'Click to export' => 'Click to export',
  'Text Import' => 'Text Import',
  'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your text file has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.' => 'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your text file has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.',
  'Text file import progress' => 'Процесс импорта текстового файла',
  'Invalid email address!' => 'Не правильный E-Mail адрес!',
  'Failed to save the email "{email}", reason: {reason}' => 'Невозможно сохранить адрес "{email}", причина: {reason}',
  'This email address is blacklisted!' => 'Этот e-mail адрес в черном списке Box-Mail!',
  'The tag "{tag}" is not defined in your list fields, we will try to create it.' => 'Тег "{tag}" не определен в списке Ваших полей, мы попытаемся его создать.',
  'The tag "{tag}" has been successfully created.' => 'Тег "{tag}" был успешно создан.',
  'The import process for list "{listName}" has successfully ended, processing {rowsCount} records!' => 'The import process for list "{listName}" has successfully ended, processing {rowsCount} records!',
);
