<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_fields" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Custom fields' => 'Настраиваемые поля',
  'List custom fields' => 'Список настраиваемых полей',
  'Text field' => 'Текстовое поле',
  'Field' => 'Field',
  'Type' => 'Тип',
  'List' => 'List',
  'Label' => 'Метка',
  'Tag' => 'Тег',
  'Default value' => 'Значение по умолчанию',
  'Help text' => 'Текст для помощи',
  'Required' => 'Обязательно',
  'Visibility' => 'Видимость',
  'This is what your subscribers will see above the input field.' => 'Это то, что Ваши подписчики увидят над полем ввода.',
  'The tag must be unique amoung the list tags. It must start with a letter, end with a letter or number and contain only alpha-numeric chars and underscores, all uppercased. The tag can be used in your templates like: [TAGNAME]' => 'Тег должен быть уникальным в списке тегов. Он должен начинаться с буквы, заканчиваться буквой или цифрой и содержать только буквенно-цифровые символы или знак подчеркивания, ВСЕ В ВЕРХНЕМ РЕГИСТРЕ. Тег может использоваться в шаблонах таких, как: [TAGNAME]',
  'In case this field is not required and you need a default value for it.' => 'Значение по умолчанию если подписчик его не заполнит сам.',
  'If you need to describe this field to your subscribers.' => 'Текстовое описание для помощи подписчикам.',
  'Whether this field must be filled in in order to submit the subscription form.' => 'Обязательно ли данное поле для заполнения.',
  'Hidden fields are not shown to subscribers.' => 'Скрыть поле и не показывать подписчику.',
  'Decide the order of the fields shown in the form.' => 'Порядок полей.',
  'Are you sure you want to remove this field? There is no coming back from this after you save the changes.' => 'Вы уверены, что хотите удалить это поле ? Восстановление не возможно.',
  'Your mail lists custom fields' => 'Пользовательские поля Вашей рассылки',
  'Add text field' => 'Добавить текстовое поле',
  'Add dropdown field' => 'Добавить выпадающее поле',
  'Add multiselect field' => 'Добавить поле в выбором',
  'New text field' => 'Новое текстовое поле',
  'New dropdown field' => 'Новое выпадающее поле',
  'Dropdown options' => 'Опции выпадающего поля',
  'Add new' => 'Добавить новое поле',
  'Option' => 'Опции',
  'Name' => 'Название',
  'Value' => 'Значение',
  'Is default' => 'По умолчанию',
  'Are you sure you want to remove this option? There is no coming back from this after you save the changes.' => 'Вы уверены, что хотите удалить эту опцию ? Восстановление будет не возможно.',
  'New multiselect field' => 'Новое поле с мультивыбором',
  'Subscriber' => 'Подписчик',
  'This email address is already registered in this list!' => 'Этот адрес почты уже есть в списке!',
  'This email address is blacklisted!' => 'Этот адрес в черном списке Box-Mail!',
  'Add date field' => 'Add date field',
  'Add datetime field' => 'Add datetime field',
  'Add textarea field' => 'Add textarea field',
  'New date field' => 'New date field',
  'New datetime field' => 'New datetime field',
  'New textarea field' => 'New textarea field',
);
