<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "misc" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View campaigns delivery logs' => 'Просмотр логов доставки сообщений',
  'Campaigns delivery logs' => 'Логи доставки',
  'View campaigns bounce logs' => 'Просмотр логов баунсов',
  'Campaigns bounce logs' => 'Логи баунсов',
  'View archived logs' => 'Просмотр архива',
  'View current logs' => 'Текущие логи',
  'Delete delivery temporary errors' => 'Удалить временные ошибки доставки',
  'Are you sure you want to delete the delivery temporary errors? Please note that this will affect running campaigns, continue only if you really know what you are doing!' => 'Are you sure you want to delete the delivery temporary errors? Please note that this will affect running campaigns, continue only if you really know what you are doing!',
  'View delivery servers usage logs' => 'Просмотр логов серверов отправки',
  'Delivery servers usage logs' => 'Логи серверов отправки',
  'View PHP info' => 'View PHP info',
  'PHP info' => 'PHP info',
);
