<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "orders" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View orders' => 'Просмотр заказов',
  'Orders' => 'Заказы',
  'Order' => 'Заказ',
  'Order no.' => 'Номер заказа',
  'Customer' => 'Пользователь',
  'Plan' => 'Тарифный план',
  'Promo code' => 'Промо-код',
  'Tax' => 'Налог',
  'Currency' => 'Currency',
  'Subtotal' => 'Стоимость',
  'Tax percent' => 'Процент налога',
  'Tax value' => 'Налоги',
  'Discount' => 'Скидка',
  'Total' => 'Итого',
  'Note' => 'Заметки',
  'If you have particular notes about this order, please type them here...' => 'Если у Вас есть особые заметки относительно данного заказа, то введите их здесь...',
  'Payment method' => 'Способ оплаты',
  'Enter your promo code here' => 'Введите Ваш промо-код тут',
  'Amount due' => 'Платежная информация',
  'due' => 'Создан',
  'View your orders' => 'Просмотр Ваших заказов',
  'View your order' => 'Информация о заказе',
  'This order applies for the "{planName}" pricing plan.' => 'Заказ на тарифный план "{planName}"',
  'Notes' => 'Детали',
  'Transaction info' => 'Информация про оплату',
  'Transaction' => 'Transaction',
  'Transaction uid' => 'Transaction uid',
  'Payment gateway name' => 'Способ платежа',
  'Payment gateway transaction' => 'Уникальный код транзакции',
  'Payment gateway response' => 'Payment gateway response',
  'Amount' => 'Сумма',
  'Status' => 'Состояние',
  'Update this order' => 'Update this order',
  'Back to orders' => 'Назад',
  'Update order' => 'Update order',
  'Customer, autocomplete enabled' => 'Заказчик',
  'Plan, autocomplete enabled' => 'Тарифный план',
  'Promo code, autocomplete enabled' => 'Промо-код',
  'The customer this order applies to, autocomplete enabled' => 'The customer this order applies to, autocomplete enabled',
  'The price plan included in this order, autocomplete enabled' => 'The price plan included in this order, autocomplete enabled',
  'The promo code applied to this order, autocomplete enabled' => 'The promo code applied to this order, autocomplete enabled',
  'View order' => 'View order',
  'Please note that any order added/changed from this area is not verified nor it goes through a payment gateway.' => 'Обратите внимание на то, что любые действия в этой панели никак не отображаются на платежных системах.',
  'Updating orders from this area is useful for offline orders mostly or for payment corrections.' => 'Обновление заказа в данной панели используется для автономной работы, либо для корректировки заказа.',
  'If the order is incomplete, pending or due and changed to complete, the customer will be affected and the price plan will be assigned properly.' => 'Вы можете изменить заказ клиента без фактической оплаты и клиент получит доступ к требуемому тарифному плану.',
  'Create order' => 'Create order',
  'Email invoice' => 'Отправить по E-Mail',
  'View invoice' => 'Экспорт в PDF',
  'Invoice' => 'Invoice',
  'Total due' => 'Total due',
  'Paid' => 'Paid',
  'Reference' => 'Reference',
  'Billing date' => 'Billing date',
  'Due date' => 'Due date',
  'Payment from' => 'Payment from',
  'Payment to' => 'Payment to',
  'Quantity' => 'Quantity',
  'Price' => 'Price',
  'Page' => 'Page',
  'of' => 'of',
  'Please try again later!' => 'Please try again later!',
  'Admin' => 'Admin',
  'Hello {name}' => 'Hello {name}',
  'As requested, attached is your order invoice with reference number: {ref}' => 'As requested, attached is your order invoice with reference number: {ref}',
  'If you have any questions regarding this invoice, please contact us.' => 'If you have any questions regarding this invoice, please contact us.',
  'Your requested invoice - {ref}' => 'Your requested invoice - {ref}',
  'The invoice has been successfully emailed!' => 'The invoice has been successfully emailed!',
);
