<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "payment_gateway_ext_offline" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Offline payment' => 'Оплата через IBF-Trade',
  'Your order is in "{status}" status, once it gets approved, your pricing plan will become active!' => 'Ваш заказ в статусе "{status}". После оплаты Ваш заказ будет активирован.',
);
