<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "payment_gateways" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Payment gateways' => 'Варианты оплаты',
  'The payment gateways are implemented as extensions, you\'ll want to enable them from the extensions area first and then manage them from here.' => 'Способы оплаты реализованы в виде расширений. Вы должны активировать их в менеджере расширений и затем сможете управлять с этой страницы.',
  'Name' => 'Название',
  'Description' => 'Описание',
  'Status' => 'Статус',
  'Sort order' => 'Сортировка',
  'Gateway detail page' => 'Gateway detail page',
);
