<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "price_plans" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View price plans' => 'Тарифы на рассылку',
  'Price plans' => 'Тарифы',
  'Plan' => 'Plan',
  'Plan uid' => 'Plan uid',
  'Customer group' => 'Группа пользователей',
  'Name' => 'Название',
  'Price' => 'Цена',
  'Description' => 'Описание',
  'Recommended' => 'Рекомендуем',
  'Create new price plan' => 'Создание нового тарифного плана',
  'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits' => 'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits',
  'The price plan name, used in customer display area, orders, etc' => 'The price plan name, used in customer display area, orders, etc',
  'The amount the customers will be charged when buying this plan' => 'The amount the customers will be charged when buying this plan',
  'A detailed description about the price plan features' => 'A detailed description about the price plan features',
  'Whether this plan has the recommended badge on it' => 'Whether this plan has the recommended badge on it',
  'Available price plans' => 'Доступные тарифные планы',
  'Select payment method' => 'Выберите способ оплаты',
  'Payment gateway selection' => 'Доступные способы оплаты',
  'Proceed to payment' => 'Выбрать',
  'Price plans payment' => 'Оформление заказа',
  'You have selected the "{planName}" pricing plan.' => 'Вы выбрали тарифный план "{planName}".',
  'Place offline order' => 'Оформить заказ',
  'Apply code' => 'Обновить стоимость',
  'Update price plan' => 'Обновление тарифного плана',
  'The provided promotional code does not exists anymore!' => 'Данный код не действителен или введен с ошибкой',
);
