<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "promo_codes" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'fixed amount' => 'Фиксированная сумма',
  'percentage' => 'Проценты',
  'View job promo codes' => 'View job promo codes',
  'Promo codes' => 'Промо-коды для скидки',
  'Jobs' => 'Jobs',
  'Code' => 'Код',
  'Type' => 'Тип',
  'Discount' => 'Скидка',
  'Total amount' => 'Общая сумма',
  'Total usage' => 'Всего (скидка)',
  'Customer usage' => 'Сколько клиентов',
  'Date start' => 'Дата начала',
  'Date end' => 'Дата окончания',
  'Create new promo code' => 'Create new promo code',
  'i.e: FREE100' => 'Например: 8764',
  'i.e: 10' => 'Например: 10',
  'i.e: 30' => 'Например: 30',
  'i.e: 1' => 'Например: 1',
  'i.e: {date}' => 'i.e: {date}',
  'i.e: 2014-11-29' => 'i.e: 2014-11-29',
  'i.e: 2014-12-29' => 'i.e: 2014-12-29',
  'The promotional code' => 'The promotional code',
  'The type of the promotional code' => 'The type of the promotional code',
  'The discount received after applying this promotional code' => 'The discount received after applying this promotional code',
  'The amount of the price plan in order for this promotional code to apply' => 'The amount of the price plan in order for this promotional code to apply',
  'The maximum number of usages for this promotional code. Set it to 0 for unlimited' => 'The maximum number of usages for this promotional code. Set it to 0 for unlimited',
  'How many times a customer can use this promotional code. Set it to 0 for unlimited' => 'How many times a customer can use this promotional code. Set it to 0 for unlimited',
  'The start date for this promotional code' => 'The start date for this promotional code',
  'The end date for this promotional code' => 'The end date for this promotional code',
  'i.e: 2014-12-02' => 'i.e: 2014-12-02',
  'i.e: 2015-01-01' => 'i.e: 2015-01-01',
  'Update promo code' => 'Update promo code',
  'i.e: 2014-12-06' => 'i.e: 2014-12-06',
  'i.e: 2015-01-05' => 'i.e: 2015-01-05',
);
