<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "sending_domains" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View sending domains' => 'Просмотр доменов для отправки',
  'Sending domains' => 'Домены отправки',
  'With sending domains you can verify the authenticity of the domain used in the campaigns FROM email field.' => 'С доменами отправки Вы можете проверить подлинность домена, используемого в рассылке в поле E-Mail отправителя.',
  'Verification is very simple, it involves adding just two DNS TXT records for the domain used in the FROM field of a campaign.' => 'Проверка (верификация) очень проста - нужно всего лишь две записи DNS TXT для домена, используемого в поле "От".',
  'Once a sending domain is verified, all future campaigns sent from the verified domain will be DKIM signed and will pass SPF validation, thus giving a higher inbox delivery rate.' => 'После отправки домен проверяется и все письма, отправленные с проверенной области будут подписаны DKIM и проверены SPF, тем самым повышая вероятность доставки и не попадания в спам.',
  'Domain' => 'Домен',
  'Customer' => 'Пользователь',
  'Domain name' => 'Доменное имя',
  'Dkim private key' => 'Приватный ключ DKIM',
  'Dkim public key' => 'Публичный ключ DKIM',
  'Locked' => 'Заблокирован',
  'Verified' => 'Варификация',
  'DKIM Signing' => 'DKIM Подпись',
  'Create new sending domain' => 'Создать новый домен отправки',
  'If this domain is verified in behalf of a customer, choose the customer.' => 'If this domain is verified in behalf of a customer, choose the customer.',
  'Domain name, i.e: example.com' => 'Адрес домена для верификации. Домен должен принадлежать Вам!',
  'Set this to yes only if you already have DNS records set for this domain.' => 'Set this to yes only if you already have DNS records set for this domain.',
  'Whether this domain is locked and the customer cannot modify or delete it.' => 'Whether this domain is locked and the customer cannot modify or delete it.',
  'Whether we should use DKIM to sign outgoing campaigns for this domain.' => 'Whether we should use DKIM to sign outgoing campaigns for this domain.',
  'DKIM private key, leave this empty to be auto-generated. Please do not edit this record unless you really know what you are doing.' => 'Приватный ключ DKIM, оставьте это поле пустым - ключ генерируется автоматически. Не изменяйте данное поле если Вы не знаете, что делаете',
  'DKIM public key, leave this empty to be auto-generated. Please do not edit this record unless you really know what you are doing.' => 'Публичный ключ DKIM, оставьте это поле пустым - ключ генерируется автоматически. Не изменяйте данное поле если Вы не знаете, что делаете.',
  'Update sending domain' => 'Обновить домен отправки',
  'Verify this domain' => 'Подтвердить этот домен',
  'Please edit your DNS records for {domain} domain and add the following TXT record: ' => 'Please edit your DNS records for {domain} domain and add the following TXT record: ',
  'For best delivery rates, your domain SPF record must look like:' => 'For best delivery rates, your domain SPF record must look like:',
  'After you have added the DNS records for your domain, please click the Verify DNS records button below to verify your domain.' => 'After you have added the DNS records for your domain, please click the Verify DNS records button below to verify your domain.',
  'Please note that it can take up to 48 hours for DNS changes to propagate. If verification fails now, please try again later.' => 'Please note that it can take up to 48 hours for DNS changes to propagate. If verification fails now, please try again later.',
  'Verify DNS records' => 'Verify DNS records',
  'Unable to retrieve the TXT records for your domain name.' => 'Unable to retrieve the TXT records for your domain name.',
  'Настройка домена отправки' => 'Настройка домена отправки',
  'Подтвердить домен' => 'Подтвердить домен',
  'Отредактируйте DNS записи в панели управления домена {domain} и внесите TXT запись: ' => 'Отредактируйте DNS записи в панели управления домена {domain} и внесите TXT запись: ',
  'Подтверждение домена' => 'Подтверждение домена',
  'Для максимального качества доставки, добавьте запись SPF следующего содержания:' => 'Для максимального качества доставки, добавьте запись SPF скопировав ее текст ниже. Если получите ошибку с невозможностью добавить запись более, чем 255 знаков, то не добавляйте запись SPF, а только DKIM',
  'После внесения записей DNS нажмите на кнопку "Верифицировать DNS записи".' => 'После внесения записей DNS нажмите на кнопку "Верифицировать DNS записи".',
  'Учитывайте, что иногда нужно до 48 часов для обновления DNS записей на хостинге. Если верификация не прошла сейчас - попробуйте позже.' => 'Учитывайте, что иногда нужно до 48 часов для обновления DNS записей на хостинге. Если верификация не прошла сейчас - попробуйте позже.',
  'Верифицировать DNS записи' => 'Верифицировать DNS записи',
  'Не удалось проверить TXT записи домена, или данные DNS еще не обновились.' => 'Не удалось проверить TXT записи домена, или данные DNS еще не обновились.',
  'Your domain has been successfully verified.' => 'Your domain has been successfully verified.',
  'Этот домен подтвержден' => 'Этот домен подтвержден',
  'Unable to find proper TXT record for your domain name, if you just added the records please wait for them to propagate.' => 'Unable to find proper TXT record for your domain name, if you just added the records please wait for them to propagate.',
  'Верификация не прошла. Возможно данные введены не правильно, либо записи DNS еще не обновились.' => 'Верификация не прошла. Возможно данные введены не правильно, либо записи DNS еще не обновились.',
  'Домен успешно верифицирован.' => 'Домен успешно верифицирован.',
  'This domain has been verified' => 'This domain has been verified',
);
