<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "themes" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View themes' => 'Просмотр тем',
  'Themes' => 'Темы',
  'Available themes' => 'Доступные темы',
  'Upload theme' => 'Загрузить тему',
  'Name' => 'Имя',
  'Description' => 'Описание',
  'Version' => 'Версия',
  'Author' => 'Автор',
  'Website' => 'Сайт',
  'Extension detail page' => 'Расширение странице подробнее',
  'Upload theme archive.' => 'Загрузить архив темы.',
  'Please note that only zip files are allowed for upload.' => 'Обратите внимание, что только zip-файлы разрешены для загрузки.',
  'Theme detail page' => 'Theme detail page',
);
