<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "tools" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Sync' => 'Объединить',
  'Subscribers' => 'Подписчики',
  'Sync lists' => 'Синхронизация рассылок',
  'Split' => 'Разбить',
  'List' => 'Список',
  'Split list' => 'Разбить список',
  'Please wait while splitting the {list} list into {num} sublists. This might take a while depending on your list size.' => 'Please wait while splitting the {list} list into {num} sublists. This might take a while depending on your list size.',
  'Back to tools' => 'Back to tools',
);
