<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "tracking_domains" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View tracking domains' => 'Просмотр треккинг-доменов',
  'Tracking domains' => 'Треккинг-домены',
  'Please note, in order for this feature to work this (sub)domain needs a dedicated IP address, otherwise all defined CNAMES for it will point to the default domain on this server.' => 'Пожалуйста, учтите, чтобы это работало на поддомене, Вам нужен отдельный IP адрес, в противном случае запись CNAMES для поддомена основого сервера.',
  'If you do not use a dedicated IP address for this domain only or you are not sure you do so, do not use this feature!' => 'Если Вы не используете выделеный IP адрес для этого домена, то не используйте эту функцию!',
  'Domain' => 'Домен',
  'Customer' => 'Пользователь',
  'Name' => 'Имя домена',
  'Create new tracking domain' => 'Создание нового треккинг-домена',
  'Please note that because of the way DNS servers work, you need to add a subdomain like tracking.your-domain.com as a DNS CNAME record and point it to {currentDomain}!' => 'Обратите внимание на то, чтобы правильно работал треккинг-домен, вы должны добавить поддомен, например tracking.your-domain.com, а также DNS CNAME запись в основном домене {currentDomain}!',
  'tracking.your-domain.com' => 'tracking.your-domain.com',
);
