<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "transactional_emails" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View transactional emails' => 'Просмотр транзакционных сообщений',
  'Transactional emails' => 'Транзакционные сообщения',
  'Sent' => 'Отправленно',
  'Unsent' => 'Не отправленно',
  'Email' => 'Email',
  'Customer' => 'Customer',
  'To email' => 'На адрес',
  'To name' => 'На имя',
  'From email' => 'From email',
  'From name' => 'From name',
  'Reply to email' => 'Reply to email',
  'Reply to name' => 'Reply to name',
  'Subject' => 'Тема',
  'Body' => 'Body',
  'Plain text' => 'Plain text',
  'Priority' => 'Priority',
  'Retries' => 'Retries',
  'Max retries' => 'Max retries',
  'Send at' => 'Время',
);
