<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "users" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View users' => 'Просмотр администраторов',
  'Users' => 'Администраторы',
  'User' => 'Администратор',
  'Language' => 'Язык',
  'First name' => 'Имя',
  'Last name' => 'Фамилия',
  'Email' => 'Email',
  'Password' => 'Пароль',
  'Timezone' => 'Часовой пояс',
  'Removable' => 'Сменный',
  'Confirm email' => 'Подтверждение email',
  'Confirm password' => 'Подтверждение пароля',
  'Create new user' => 'Создать нового администратора',
  'You are impersonating the customer {customerName}.' => 'Вы в роли пользователя {customerName}.',
  'Please click {linkBack} to logout in order to finish impersonating.' => 'Пожалуйста, нажмите {linkBack}, чтобы выйти из этой роли.',
  'Update account' => 'Обновление учетной записи',
  'Update your account data.' => 'Обновление данных Вашей учетной записи.',
  'Please login' => 'Please login',
  'Remember me' => 'Remember me',
  'Forgot password?' => 'Forgot password?',
  'Invalid login credentails.' => 'Invalid login credentails.',
  'Avatar' => 'Avatar',
  'New avatar' => 'New avatar',
  'You are not allowed to update the master administrator!' => 'You are not allowed to update the master administrator!',
  'Retrieve a new password for your account.' => 'Retrieve a new password for your account.',
  'Request' => 'Request',
  'Reset key' => 'Reset key',
  'Ip address' => 'Ip address',
  'Please follow the following url in order to reset your password:' => 'Please follow the following url in order to reset your password:',
  'If for some reason you cannot click the above url, please paste this one into your browser address bar:' => 'If for some reason you cannot click the above url, please paste this one into your browser address bar:',
  'Password reset request!' => 'Password reset request!',
  'Your new login is:' => 'Your new login is:',
  'You can login by clicking <a href="{loginUrl}">here</a>.' => 'You can login by clicking <a href="{loginUrl}">here</a>.',
  'If for some reason the link doesn\'t work, please copy the following url into your browser address bar:' => 'If for some reason the link doesn\'t work, please copy the following url into your browser address bar:',
  'Group' => 'Group',
  'Update user' => 'Update user',
);
