<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "api_keys" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Key' => 'Ключ',
  'Customer' => 'Клиент',
  'Public key' => 'Публичные ключ',
  'Private key' => 'Приватный ключ',
  'Ip whitelist' => 'Белый список IP',
  'Ip blacklist' => 'Черный список IP',
  '123.123.123.123, 111.111.111.111' => '123.123.123.123, 111.111.111.111',
  '231.231.231.231, 222.222.222.222' => '231.231.231.231, 222.222.222.222',
  'Generate new key' => 'Генерировать новый ключ',
  'Your API url is: {url}' => 'Ваш URL для API: {url}',
  'Api keys' => 'API ключи',
  'A new API access has been added:<br />Public key: {public} <br />Private key: {private}' => 'Новый API ключ был добавлен:<br />Публичный ключ: {public} <br />Приватный ключ: {private}',
  'Update api keys' => 'Редактировать API ключи',
  'Requested API access has been successfully removed!' => 'Запрошенный доступ к API был успешно удален!',
);
