<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "articles" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Articles' => 'Articles',
  'Article categories' => 'Article categories',
  'View zones' => 'View zones',
  'View article categories' => 'View article categories',
  'Categories' => 'Categories',
  'Create new article category' => 'Create new article category',
  'Update article category' => 'Update article category',
  'View countries' => 'View countries',
  'View articles' => 'View articles',
  'Create new article' => 'Create new article',
  'Update article' => 'Update article',
  'Article' => 'Article',
  'Category' => 'Category',
  'Parent' => 'Parent',
  'Name' => 'Name',
  'Slug' => 'Slug',
  'Description' => 'Description',
  'My category name' => 'My category name',
  'my-category-name' => 'my-category-name',
  'Title' => 'Title',
  'Content' => 'Content',
  'Published' => 'Published',
  'Unpublished' => 'Unpublished',
  'My article title' => 'My article title',
  'my-article-title' => 'my-article-title',
  'List of helpful articles' => 'List of helpful articles',
  'We\'re sorry, but for now there is no published article!' => 'We\'re sorry, but for now there is no published article!',
  'All articles filled in under this category' => 'All articles filled in under this category',
  'We\'re sorry, but this category doesn\'t have any published article yet!' => 'We\'re sorry, but this category doesn\'t have any published article yet!',
  'Helpful articles' => 'Helpful articles',
  'This article is unpublished, only site admins can see it!' => 'This article is unpublished, only site admins can see it!',
  'Related articles' => 'Related articles',
);
