<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "countries" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Please note that removing this country will also remove every record that depends on it, such as zones, taxes, customer companies, etc!' => 'Please note that removing this country will also remove every record that depends on it, such as zones, taxes, customer companies, etc!',
  'Are you still sure you want to remove this country? There is no coming back after you do it!' => 'Are you still sure you want to remove this country? There is no coming back after you do it!',
  'View countries' => 'View countries',
  'Countries' => 'Countries',
  'Create new country' => 'Create new country',
  'Update country' => 'Update country',
  'Confirm country removal' => 'Confirm country removal',
  'Country' => 'Country',
  'Name' => 'Name',
  'Code' => 'Code',
);
