<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "dashboard" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Are you sure you want to remove all blacklist monitors?' => 'Вы уверены, что хотите удалить все мониторинги черных списков?',
  'Are you sure you want to remove all blacklisted emails?' => 'уверены, что хотите удалить все email адреса из черного списка?',
  'Recent activity' => 'Последняя активность',
  'Dashboard' => 'Панель управления',
  'Customers' => 'Клиенты',
  'Campaigns' => 'Кампании',
  'Lists' => 'Списки',
  'Subscribers' => 'Подписчики',
  'Segments' => 'Сегменты',
  'Delivery servers' => 'Серверы доставки',
  'Are you sure you want to remove all suppressed emails?' => 'Вы уверены, что хотите удалить все заблокированные email адреса?',
  '{n} months growth' => '{n} месячный рост',
  'Templates' => 'Шаблоны',
);
