<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "dashboard" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Are you sure you want to remove all blacklist monitors?' => 'Are you sure you want to remove all blacklist monitors?',
  'Are you sure you want to remove all blacklisted emails?' => 'Are you sure you want to remove all blacklisted emails?',
  'Recent activity' => 'Recent activity',
  'Dashboard' => 'Dashboard',
  'Customers' => 'Customers',
  'Campaigns' => 'Campaigns',
  'Lists' => 'Lists',
  'Subscribers' => 'Subscribers',
  'Segments' => 'Segments',
  'Delivery servers' => 'Delivery servers',
  'Are you sure you want to remove all suppressed emails?' => 'Are you sure you want to remove all suppressed emails?',
  '{n} months growth' => '{n} months growth',
  'Templates' => 'Templates',
);
