<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "guest_fail_attempt" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View guest fail attempts' => 'View guest fail attempts',
  'Guest fail attempts' => 'Guest fail attempts',
  'Attempt' => 'Attempt',
  'Ip address' => 'Ip address',
  'Ip address hash' => 'Ip address hash',
  'User agent' => 'User agent',
  'Place' => 'Place',
);
