<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ip_location" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Ip location services' => 'Ip location services',
  'Name' => 'Name',
  'Description' => 'Description',
  'Status' => 'Status',
  'Sort order' => 'Sort order',
  'Service detail page' => 'Service detail page',
  'Ip location services are used to collect location data(country, zone, city) when subscribers open the email campaigns or when they click on a trackable url, etc.' => 'Ip location services are used to collect location data(country, zone, city) when subscribers open the email campaigns or when they click on a trackable url, etc.',
  'This data is then used in campaign reports to show you the exact location where the email campaign has been opened or the location from where the subscriber clicked a link from within the campaign.' => 'This data is then used in campaign reports to show you the exact location where the email campaign has been opened or the location from where the subscriber clicked a link from within the campaign.',
  'Please note, data accuracy will vary between the services. You should test the service website before enable.' => 'Please note, data accuracy will vary between the services. You should test the service website before enable.',
  'Location' => 'Location',
  'Ip address' => 'Ip address',
  'Country code' => 'Country code',
  'Country name' => 'Country name',
  'Zone name' => 'Zone name',
  'City name' => 'City name',
  'Latitude' => 'Latitude',
  'Longitude' => 'Longitude',
);
