<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_pages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'List' => 'List',
  'Type' => 'Type',
  'Content' => 'Content',
  'The following tag is required but was not found in your content: {tag}' => 'The following tag is required but was not found in your content: {tag}',
  'Your unsubscribe form url is:' => 'Your unsubscribe form url is:',
  'Preview it now!' => 'Preview it now!',
  'Select another list page to edit' => 'Select another list page to edit',
  'Your subscribe form url is:' => 'Your subscribe form url is:',
  'Pages' => 'Pages',
  'List pages' => 'List pages',
);
