<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_fields" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Value' => 'Value',
  'Field' => 'Field',
  'Subscriber' => 'Subscriber',
  'Type' => 'Type',
  'List' => 'List',
  'Label' => 'Label',
  'Tag' => 'Tag',
  'Default value' => 'Default value',
  'Help text' => 'Help text',
  'Required' => 'Required',
  'Visibility' => 'Visibility',
  'Sort order' => 'Sort order',
  'The {attribute} attribute must be unique in the mail list!' => 'The {attribute} attribute must be unique in the mail list!',
  '"{tagName}" is reserved!' => '"{tagName}" is reserved!',
  'This is what your subscribers will see above the input field.' => 'This is what your subscribers will see above the input field.',
  'The tag must be unique amoung the list tags. It must start with a letter, end with a letter or number and contain only alpha-numeric chars and underscores, all uppercased. The tag can be used in your templates like: [TAGNAME]' => 'The tag must be unique amoung the list tags. It must start with a letter, end with a letter or number and contain only alpha-numeric chars and underscores, all uppercased. The tag can be used in your templates like: [TAGNAME]',
  'In case this field is not required and you need a default value for it.' => 'In case this field is not required and you need a default value for it.',
  'If you need to describe this field to your subscribers.' => 'If you need to describe this field to your subscribers.',
  'Whether this field must be filled in in order to submit the subscription form.' => 'Whether this field must be filled in in order to submit the subscription form.',
  'Hidden fields are not shown to subscribers.' => 'Hidden fields are not shown to subscribers.',
  'Decide the order of the fields shown in the form.' => 'Decide the order of the fields shown in the form.',
  'Option' => 'Option',
  'Name' => 'Name',
  'Is default' => 'Is default',
  'Identifier' => 'Identifier',
  'Class alias' => 'Class alias',
  'Description' => 'Description',
  'Custom fields' => 'Custom fields',
  'There is no field type defined yet, please contact the administrator.' => 'There is no field type defined yet, please contact the administrator.',
  'Your mail lists custom fields' => 'Your mail lists custom fields',
  'List custom fields' => 'List custom fields',
  'Your mail list does not have any field defined.' => 'Your mail list does not have any field defined.',
  'This email address is blacklisted!' => 'This email address is blacklisted!',
  'This email address is already registered in this list!' => 'This email address is already registered in this list!',
  'Text field' => 'Text field',
  'Are you sure you want to remove this field? There is no coming back from this after you save the changes.' => 'Are you sure you want to remove this field? There is no coming back from this after you save the changes.',
  'Add text field' => 'Add text field',
  'New text field' => 'New text field',
  'Missing the EMAIL tag, this is not acceptable!' => 'Missing the EMAIL tag, this is not acceptable!',
  'Multiselect field' => 'Multiselect field',
  'Dropdown options' => 'Dropdown options',
  'Are you sure you want to remove this option? There is no coming back from this after you save the changes.' => 'Are you sure you want to remove this option? There is no coming back from this after you save the changes.',
  'Add multiselect field' => 'Add multiselect field',
  'New multiselect field' => 'New multiselect field',
  'Datetime field' => 'Datetime field',
  'Add datetime field' => 'Add datetime field',
  'New datetime field' => 'New datetime field',
  'Dropdown field' => 'Dropdown field',
  'Add dropdown field' => 'Add dropdown field',
  'New dropdown field' => 'New dropdown field',
  'Date field' => 'Date field',
  'Add date field' => 'Add date field',
  'New date field' => 'New date field',
  'State field' => 'State field',
  'Add state field' => 'Add state field',
  'New state field' => 'New state field',
  'Country field' => 'Country field',
  'Add country field' => 'Add country field',
  'New country field' => 'New country field',
  'Textarea field' => 'Textarea field',
  'Add textarea field' => 'Add textarea field',
  'New textarea field' => 'New textarea field',
);
