<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "mailer" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'System testing mailer, only simulate sending.' => 'System testing mailer, only simulate sending.',
  'A fully compliant mailer.' => 'A fully compliant mailer.',
  'A very fast mailer.' => 'A very fast mailer.',
);
