<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "messages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'See all messages' => 'Посмотреть все сообщения',
  'View messages' => 'Посмотреть сообщения',
  'Messages' => 'Сообщения',
  'Create new message' => 'Создать новое сообщение',
  'Update message' => 'Обновить сообщения',
  'View message' => 'Прочитать сообщение',
  'All messages were marked as seen!' => 'Все сообщения были помечены как отправленные!',
  'You have {n} unread messages!' => 'У вас {n} сообщений!',
  'Message' => 'Сообщение',
  'Customer' => 'Клиент',
  'Title' => 'Заголовок',
  'Unseen' => 'Непрочитано',
  'Seen' => 'Прочитано',
  'User' => 'Пользователь',
  'here' => 'здесь',
);
