<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "options" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Category' => 'Категория',
  'Key' => 'Ключ',
  'Value' => 'Значение',
  'Is serialized' => 'Сериализован ли',
);
