<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "price_plans" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Price plans' => 'Price plans',
  'View price plans' => 'View price plans',
  'Create new price plan' => 'Create new price plan',
  'Update price plan' => 'Update price plan',
  'Plan' => 'Plan',
  'Plan uid' => 'Plan uid',
  'Customer group' => 'Customer group',
  'Name' => 'Name',
  'Price' => 'Price',
  'Description' => 'Description',
  'Recommended' => 'Recommended',
  'Visible' => 'Visible',
  'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits' => 'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits',
  'The price plan name, used in customer display area, orders, etc' => 'The price plan name, used in customer display area, orders, etc',
  'The amount the customers will be charged when buying this plan' => 'The amount the customers will be charged when buying this plan',
  'A detailed description about the price plan features' => 'A detailed description about the price plan features',
  'Whether this plan has the recommended badge on it' => 'Whether this plan has the recommended badge on it',
  'Whether this plan is visible in customers area' => 'Whether this plan is visible in customers area',
  'Price plan' => 'Price plan',
  'Submit payment' => 'Submit payment',
  'Place offline order' => 'Place offline order',
  'You have selected the "{planName}" pricing plan.' => 'You have selected the "{planName}" pricing plan.',
  'Apply code' => 'Apply code',
  'Available price plans' => 'Available price plans',
  'Select payment method' => 'Select payment method',
  'Payment gateway selection' => 'Payment gateway selection',
  'Proceed to payment' => 'Proceed to payment',
  'Unable to load the payment gateway!' => 'Unable to load the payment gateway!',
  'Invalid payment gateway setup!' => 'Invalid payment gateway setup!',
  'The specified price plan is invalid!' => 'The specified price plan is invalid!',
  'Selected price plan allows {n} {w} but you already have {m}, therefore you cannot apply for the plan!' => 'Selected price plan allows {n} {w} but you already have {m}, therefore you cannot apply for the plan!',
  'Unable to set a correct curency!' => 'Unable to set a correct curency!',
  'Price plans payment' => 'Price plans payment',
  'Unable to load payment data!' => 'Unable to load payment data!',
  'Invalid currency specified!' => 'Invalid currency specified!',
  'Cannot save your order!' => 'Cannot save your order!',
  'The provided promotional code does not exists anymore!' => 'The provided promotional code does not exists anymore!',
  'This promo code requires that select a price plan that costs at least {amount}!' => 'This promo code requires that select a price plan that costs at least {amount}!',
  'You have reached the maximum usage times for this promo code!' => 'You have reached the maximum usage times for this promo code!',
  'This promo code has reached the maximum usage times!' => 'This promo code has reached the maximum usage times!',
  'The promo code has been successfully applied!' => 'The promo code has been successfully applied!',
);
