<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "themes" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Available themes' => 'Available themes',
  'Upload theme' => 'Upload theme',
  'Name' => 'Name',
  'Description' => 'Description',
  'Version' => 'Version',
  'Author' => 'Author',
  'Website' => 'Website',
  'Theme detail page' => 'Theme detail page',
  'Upload theme archive.' => 'Upload theme archive.',
  'Please note that only zip files are allowed for upload.' => 'Please note that only zip files are allowed for upload.',
  'View themes' => 'View themes',
  'Themes' => 'Themes',
  'Theme settings' => 'Theme settings',
  'Your theme has been successfully uploaded!' => 'Your theme has been successfully uploaded!',
  'Please select a theme archive for upload!' => 'Please select a theme archive for upload!',
  'The theme "{name}" has been successfully enabled!' => 'The theme "{name}" has been successfully enabled!',
  'The theme "{name}" has been successfully disabled!' => 'The theme "{name}" has been successfully disabled!',
  'The theme "{name}" has been successfully deleted!' => 'The theme "{name}" has been successfully deleted!',
  'Visit website' => 'Visit website',
  'The theme does not exists.' => 'The theme does not exists.',
  'The theme is already enabled.' => 'The theme is already enabled.',
  'Enabling the theme {theme} has failed.' => 'Enabling the theme {theme} has failed.',
  'The theme could not be disabled.' => 'The theme could not be disabled.',
  'The theme cannot be deleted.' => 'The theme cannot be deleted.',
);
