<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "update" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Update application' => 'Update application',
  'Your current application version is {version}' => 'Your current application version is {version}',
  'The update process will try to update it to version {version}' => 'The update process will try to update it to version {version}',
  'Please backup all your data before proceeding and note that the update process might take a while depending on your database size, just wait for it to finish.' => 'Please backup all your data before proceeding and note that the update process might take a while depending on your database size, just wait for it to finish.',
  'Your application has been moved offline until the update process is done.' => 'Your application has been moved offline until the update process is done.',
  'Start update process' => 'Start update process',
  'Updating to version {version}.' => 'Updating to version {version}.',
  'Updated to version {version} successfully.' => 'Updated to version {version} successfully.',
  'Updating to version {version} failed with: {message}' => 'Updating to version {version} failed with: {message}',
  'Congratulations, your application has been successfully updated to version {version}' => 'Congratulations, your application has been successfully updated to version {version}',
  'Please note, depending on your database size it is better to run the command line update tool instead.' => 'Please note, depending on your database size it is better to run the command line update tool instead.',
  'In order to run the command line update tool, you must run the following command from a ssh shell:' => 'In order to run the command line update tool, you must run the following command from a ssh shell:',
  'Update' => 'Update',
  'Application update' => 'Application update',
  'This version adds new fields for delivery servers and some of them are required. Because of this, all delivery servers have been marked as inactive. Please review the settings and validate the servers once again.' => 'This version adds new fields for delivery servers and some of them are required. Because of this, all delivery servers have been marked as inactive. Please review the settings and validate the servers once again.',
  'Please note that starting with this version update, we deprecated the redis queue feature!' => 'Please note that starting with this version update, we deprecated the redis queue feature!',
  'Version {version} brings a new cron job that you have to add to run once at 2 minutes. After addition, it must look like: {cron}' => 'Version {version} brings a new cron job that you have to add to run once at 2 minutes. After addition, it must look like: {cron}',
  'Version {version} brings a new cron job that you have to add to run once a day. After addition, it must look like: {cron}' => 'Version {version} brings a new cron job that you have to add to run once a day. After addition, it must look like: {cron}',
  'Version {version} brings a new cron job that you have to add to run once at 20 minutes. After addition, it must look like: {cron}' => 'Version {version} brings a new cron job that you have to add to run once at 20 minutes. After addition, it must look like: {cron}',
  'Starting with version {version}, the "process-subscribers" command is no longer needed, please disable it from your crons!' => 'Starting with version {version}, the "process-subscribers" command is no longer needed, please disable it from your crons!',
  'Version {version} brings a new cron job that you have to add to run each hour. After addition, it must look like: {cron}' => 'Version {version} brings a new cron job that you have to add to run each hour. After addition, it must look like: {cron}',
);
