<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "users" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Users' => 'Users',
  'Update your account data.' => 'Update your account data.',
  'Go to login' => 'Go to login',
  'Sign in to start your session' => 'Sign in to start your session',
  'Forgot password?' => 'Forgot password?',
  'Please follow the following url in order to reset your password:' => 'Please follow the following url in order to reset your password:',
  'If for some reason you cannot click the above url, please paste this one into your browser address bar:' => 'If for some reason you cannot click the above url, please paste this one into your browser address bar:',
  'Your new login is:' => 'Your new login is:',
  'Email' => 'Email',
  'Password' => 'Password',
  'You can login by clicking <a href="{loginUrl}">here</a>.' => 'You can login by clicking <a href="{loginUrl}">here</a>.',
  'If for some reason the link doesn\'t work, please copy the following url into your browser address bar:' => 'If for some reason the link doesn\'t work, please copy the following url into your browser address bar:',
  'Remember me' => 'Remember me',
  'Unable to login with the given identity!' => 'Unable to login with the given identity!',
  'Update user group' => 'Update user group',
  'View users' => 'View users',
  'Create new user' => 'Create new user',
  'You are not allowed to update the master administrator!' => 'You are not allowed to update the master administrator!',
  'Update user' => 'Update user',
  'Please login' => 'Please login',
  'Password reset request!' => 'Password reset request!',
  'Retrieve a new password for your account.' => 'Retrieve a new password for your account.',
  'Update account' => 'Update account',
  'Invalid login credentials.' => 'Invalid login credentials.',
  'Request' => 'Request',
  'User' => 'User',
  'Reset key' => 'Reset key',
  'Ip address' => 'Ip address',
  'Token' => 'Token',
  'Language' => 'Language',
  'Group' => 'Group',
  'First name' => 'First name',
  'Last name' => 'Last name',
  'Timezone' => 'Timezone',
  'Avatar' => 'Avatar',
  'New avatar' => 'New avatar',
  'Removable' => 'Removable',
  'Confirm email' => 'Confirm email',
  'Confirm password' => 'Confirm password',
  'The avatars storage directory({path}) does not exists and cannot be created!' => 'The avatars storage directory({path}) does not exists and cannot be created!',
  'Cannot move the avatar into the correct storage folder!' => 'Cannot move the avatar into the correct storage folder!',
  'You are impersonating the customer {customerName}.' => 'You are impersonating the customer {customerName}.',
  'Please click {linkBack} to logout in order to finish impersonating.' => 'Please click {linkBack} to logout in order to finish impersonating.',
);
