<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "user_groups" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Access' => 'Access',
  'Allow all' => 'Allow all',
  'Deny all' => 'Deny all',
  'View user groups' => 'View user groups',
  'User groups' => 'User groups',
  'Create new user group' => 'Create new user group',
  'You do not have the permission to access this resource!' => 'You do not have the permission to access this resource!',
  'Group' => 'Group',
  'Name' => 'Name',
  'Users count' => 'Users count',
  'Route' => 'Route',
  'Description' => 'Description',
  'Controller' => 'Controller',
  'Action' => 'Action',
);
