<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "zones" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Please note that removing this zone will also remove every record that depends on it, such as taxes, customer companies, etc!' => 'Пожалуйста, обратите внимание, что удаляя эту зону повлечет за собой удаление каждой записи, которая к ней относится (напр. налоги, компании клиента и т. д.)!',
  'Are you still sure you want to remove this zone? There is no coming back after you do it!' => 'Вы действительно хотите удалить эту зону? Пути обратно не будет!!',
  'View zones' => 'Просмотреть зоны',
  'Zones' => 'Зоны',
  'Create new zone' => 'Создать новую зону',
  'Update zone' => 'Редактировать зону',
  'Confirm zone removal' => 'Подтвердите удаление зоны',
  'Zone' => 'Зона',
  'Country' => 'Страна',
  'Name' => 'Имя',
  'Code' => 'Код',
);
